import { useTranslation } from 'react-i18next'
import { QuizAccordion } from '@/components/quiz-accordion'
import { Callout, ContentSection, InfoCard, LeadCard, ResponsiveTable, SourceList, WeekLayout } from '@/components/week-layout'
import type { Locale } from '@/i18n'

const copy = {
  zh: {
    title: 'Teams, Thinking & Communication', subtitle: '核心知识与 Quiz 速查',
    summary: '团队先建立共同规则，经历发展阶段，用合适的思考流程做决策，再以专业、低冲突的方式沟通。',
    tags: ['9 份阅读', '4 个知识模块', '13 道自测', '约 8 分钟复习'],
    toc: ['知识地图', 'Social Contract', 'Tuckman + Z-Process', 'Six Thinking Hats', '专业沟通', 'Quiz Ready', '资料来源'],
    overview: { title: '30 秒建立知识地图', intro: '记住四个动作：Agree → Develop → Think → Communicate。', cards: [
      ['Agree · 先约定', 'Social Contract 由全体成员共同定义可接受的行为和工作方式，建立 ownership、trust 与 psychological safety。'],
      ['Develop · 再发展', 'Tuckman 解释团队如何从陌生走向高绩效；Z-Process 解释一个想法如何在成熟团队中走向落地。'],
      ['Think · 同步思考', 'Six Thinking Hats 让成员同时采用同一种思考视角，减少争辩式讨论和 spaghetti thinking。'],
      ['Communicate · 清晰表达', 'Email etiquette 管理专业性；I-statements 用感受、事件与请求替代指责。'],
    ]},
    contract: {
      title: 'Social Contract：团队如何一起工作', intro: '它不是经理下发的规章，而是团队对行为、沟通和协作方式形成的共同承诺，也叫 Working Agreement。',
      definition: 'A set of agreements made within the team that describes how members will behave and work together.',
      principles: ['由全体成员共同创建和修改；缺席会削弱 ownership。', '必须获得全员认同，并在团队生命周期内持续存在。', '可随团队变化而更新，但不能凌驾于组织政策之上。', '任何成员都可以提醒偏离约定的行为。'],
      process: ['全体成员参加 workshop，说明 What 与 Why。', '个人写下期望行为，再按主题归类。', '逐项讨论含义、边界与分歧处理方式。', '仅保留全员同意并愿意互相负责的条目。', '签署并放在可见位置，定期回顾和更新。'],
      clue: '它的力量来自 shared ownership，而不是纸张、签名或管理层权威。',
      tableHeaders: ['约定领域', '典型内容', '目的'],
      tableRows: [['Meetings', '准时、有 agenda、全员有发言机会、手机静音', '提高参与、公平与效率'], ['Communication', '尽早提出问题、不打断、不做无依据假设、共享文件', '提高透明度与心理安全'], ['Agile work', '任务 ownership、及时更新 JIRA、谁破坏 build 谁修复', '强化责任与可见性']],
    },
    development: {
      title: '团队发展：阶段与工作流', intro: 'Tuckman 看团队关系如何成熟；Z-Process 看想法如何经过不同角色成熟。两者都不是一次性直线。',
      stages: [['Forming', '成员相互认识，角色和目标尚不清晰，依赖 leader 指引。', '澄清目标、角色，建立 team charter。'], ['Storming', '成员测试边界，工作方式、权威或任务分配引发冲突。', '尽早处理冲突，确保安全且人人能发言。'], ['Norming', '差异逐步解决，成员欣赏彼此优势，信任和反馈增加。', '促进连接、反馈与个人责任。'], ['Performing', '团队高信任、低监督、角色灵活，能高效完成目标。', '授权、发展成员，持续观察退步信号。'], ['Adjourning', '项目结束或团队解散，成员可能因离别与不确定而不适。', '庆祝成果、反馈、支持下一步。']],
      nonLinear: 'Tuckman 不是单向阶梯。新成员加入、方向改变或压力上升，都可能让团队退回较早阶段。', zTitle: 'Z-Process：让想法变成熟',
      roles: [['C', 'Creator', '提出愿景与新想法，关注 possibilities。'], ['A', 'Advancer', '连接客户或用户，取得 feedback，判断接受度。'], ['R', 'Refiner', '研究、批判分析、找缺陷，把想法推进为 prototype。'], ['E', 'Executor', '把成熟方案变成现实，关注 realities 和实施。']],
      risk: 'Creator → Refiner 会跳过用户反馈；Creator → Executor 会要求执行者实现尚未验证、尚未完善的想法。流程可迭代，但不应任意跳过角色。',
    },
    hats: {
      title: 'Six Thinking Hats：六种思考镜头', intro: '每顶帽子是临时思考模式，不是固定人格。Parallel thinking 的关键是所有人同时戴同一顶帽子。',
      items: [['White · Facts', '已知数据、可用信息、还缺少什么；保持中立。', 'What do we know?', '#f7f5ed'], ['Red · Feelings', '情绪、直觉与 gut reaction；可以表达但不要求论证。', 'How do we feel?', '#dc554e'], ['Black · Risks', '限制、错误、障碍和最坏情况；检查为何可能失败。', 'What could go wrong?', '#242836'], ['Yellow · Benefits', '优势、价值、可行性与成功理由。', 'What value can this create?', '#e4bc3b'], ['Green · Ideas', '创意、替代方案和 provocation；暂时放下判断。', 'What else could we try?', '#54a767'], ['Blue · Process', '管理目标、顺序、时间、总结与下一步。', 'How will we think and decide?', '#4c79c6']],
      sequence: 'Blue → White → Red → Green → Yellow → Black → Blue', sequenceNote: '顺序可按任务调整，但通常以 Blue 开始界定流程，并以 Blue 结束、记录决定与行动。',
      trap: '不要把人固定标签成 black-hat person、频繁乱切帽子、让 Black 太早压制 Green，或忘记 Blue 的过程管理。',
    },
    communication: {
      title: '专业沟通：Email + Questioning + I-statements', intro: '共同目标是减少误解与防御：邮件强调结构和情境，提问获取高质量反馈，I-statements 对自己的感受负责并提出请求。',
      email: ['Subject line 清晰、具体，与内容一致。', '有合适 salutation；正文简短但提供必要 context。', '校对拼写语法，并根据文化与对象调整 formalities 和 tone。', '谨慎使用 emoji、感叹号、幽默、俚语与 urgent。', 'CC 让收件人彼此可见；BCC 隐藏地址，群发时保护隐私。', '附件大小合理，结尾给出明确 next step 和 deadline。', '通常在 24 小时内回复，或说明预计回复时间；签名保持专业。'],
      formula: 'I feel（感受）+ when（事件/问题）+ I would like（期望/方案）', iNote: '提高 assertiveness，不直接责怪对方；降低 defensiveness，促进 empathy、cooperation 与 conflict resolution。',
      bad: '伪 I-statement：“I feel like you don’t care.” 看似以 I 开头，实质仍在评价对方。', good: '更好：“I feel worried when I don’t receive an update. I’d like us to agree on a check-in time.”',
      questions: [['Open · Explore', 'What aspects of our current design should we improve?', '会议开头广泛收集反馈，不能只以 yes/no 回答。'], ['Reflective · Clarify', 'It sounds like you’re concerned about the scope—is that right?', '中段反映观点或感受，检查理解并鼓励继续解释。'], ['Closed · Confirm', 'Should we complete the prototype before Friday?', '结尾确认事实、选择、承诺、deadline 与 next step。']],
      tableHeaders: ['概念', '关注点', '不是'], tableRows: [['Social Contract', '团队共同的行为与协作规范', '管理层命令；不可改变的制度'], ['I-statement', '我的真实感受、触发事件、希望发生什么', '用 I feel 包装对他人的判断'], ['Effective questioning', '让问题类型匹配会议阶段与所需反馈', '全程只用开放题或 Leading questions'], ['Professional email', '清晰、尊重、适应对象与文化情境', '越正式越好；所有人都应 CC']],
    },
    quiz: {
      title: 'Quiz Ready：最可能怎么考', intro: '优先记忆顺序、映射、区别与情境应用。点击题目展开答案。',
      items: [['哪一项不属于 Social Contract 的正确特征？', '“可以覆盖组织政策”不正确。它不能 override policies，并应由全体成员共同创建和修改。'], ['为什么缺席成员会削弱 Social Contract？', '参与创建会产生 ownership、commitment 和 accountability；未参与者通常较少认同。'], ['成员开始挑战边界、领导方式和任务安排，团队处于哪个阶段？', 'Storming。应澄清角色、尽早处理冲突并保护开放讨论。'], ['Performing 团队是否会退回较早阶段？', '会。新成员、目标改变或环境压力可能扰乱 group dynamics。'], ['写出 Tuckman 五阶段的完整顺序。', 'Forming → Storming → Norming → Performing → Adjourning（也称 Mourning）。'], ['Z-Process 的四角色顺序是什么？', 'Creator → Advancer → Refiner → Executor，可记作 CARE。'], ['Creator 直接把想法交给 Executor，主要风险是什么？', '想法尚未取得用户反馈、完成批判分析和原型化，执行者会面对模糊、未验证的要求。'], ['哪顶帽子分别对应 facts、feelings、risks、benefits、ideas、process？', 'White、Red、Black、Yellow、Green、Blue。'], ['为什么 Blue Hat 常在开始和结束时使用？', '开始时界定问题、目标、规则和顺序；结束时总结、记录决定并明确 next steps。'], ['Parallel thinking 与普通辩论最关键的区别是什么？', '所有人同时采用同一视角；帽子是临时镜头而不是人格标签。'], ['“I feel like you are careless” 为什么不是好的 I-statement？', '它是对他人的判断而非真实感受，会触发防御；应表达 feeling、事件与请求。'], ['CC 与 BCC 有什么区别？专业邮件还应明确什么？', 'CC 地址彼此可见；BCC 隐藏地址。邮件还应有清晰 subject、tone、context、action/deadline 与 signature。'], ['与 mentor 开会时，Open、Reflective 和 Closed questions 分别何时使用？', 'Open 用于开头探索；Reflective 用于中段澄清；Closed 用于结尾确认承诺。记忆：Explore → Clarify → Confirm。']],
      memory: [['FSNPA', 'Forming → Storming → Norming → Performing → Adjourning'], ['CARE', 'Creator → Advancer → Refiner → Executor'], ['W R B Y G B', 'Facts · Feelings · Risks · Benefits · Ideas · Process'], ['Open → Reflective → Closed', 'Explore → Clarify → Confirm'], ['Feel → Event → Request', 'I feel… when… I would like…']],
    },
    sources: ['Agile Ways of Working — Social Contracts', 'Social Contracts for Agile Teams', 'Forming, Storming, Norming, and Performing', 'The Happy Manager — Teamwork Theory', 'Using the Z-Process to Develop an Effective Team Workflow', 'Six Thinking Hats Technique by Edward de Bono', '15 Email Etiquette Rules for Every Professional', 'How Using I Feel Statements Can Help You Communicate', 'Euson — Listening, Questioning and Feedback'],
  },
  en: {
    title: 'Teams, Thinking & Communication', subtitle: 'Core knowledge and quiz guide',
    summary: 'Teams first agree how to work, move through stages of development, use structured thinking to decide, and communicate professionally with less conflict.',
    tags: ['9 readings', '4 knowledge blocks', '13 self-checks', '≈ 8 min review'], toc: ['Knowledge map', 'Social Contract', 'Tuckman + Z-Process', 'Six Thinking Hats', 'Professional communication', 'Quiz Ready', 'Sources'],
    overview: { title: 'Build the knowledge map in 30 seconds', intro: 'Remember four actions: Agree → Develop → Think → Communicate.', cards: [['Agree first', 'A Social Contract lets all members define acceptable behaviour and work practices, building ownership, trust, and psychological safety.'], ['Develop together', 'Tuckman explains how relationships mature; the Z-Process explains how an idea moves through a mature team into delivery.'], ['Think in parallel', 'Six Thinking Hats asks everyone to use the same perspective at the same time, reducing debate and spaghetti thinking.'], ['Communicate clearly', 'Email etiquette supports professionalism; I-statements replace blame with feelings, events, and constructive requests.']] },
    contract: {
      title: 'Social Contract: how the team works together', intro: 'This is not a manager-issued rulebook. It is the team’s shared commitment about behaviour, communication, and collaboration—also called a Working Agreement.', definition: 'A set of agreements made within the team that describes how members will behave and work together.',
      principles: ['All members create and revise it; absence weakens ownership.', 'Everyone must agree, and the contract remains active throughout the team lifecycle.', 'It can evolve with the team but cannot override organisational policy.', 'Any member may call attention to behaviour that departs from the agreement.'], process: ['Bring every member to a workshop and explain what and why.', 'Write expected behaviours individually, then group them by theme.', 'Discuss meaning, boundaries, and how disagreement will be handled.', 'Keep only items everyone accepts and will hold each other accountable for.', 'Sign it, keep it visible, and review it regularly.'], clue: 'Its power comes from shared ownership—not paper, signatures, or management authority.',
      tableHeaders: ['Area', 'Typical agreement', 'Purpose'], tableRows: [['Meetings', 'Be punctual, use an agenda, give everyone a voice, silence phones', 'Improve participation, fairness, and efficiency'], ['Communication', 'Raise problems early, do not interrupt or assume, share files', 'Improve transparency and psychological safety'], ['Agile work', 'Own tasks, update JIRA, fix the build you break', 'Strengthen accountability and visibility']],
    },
    development: {
      title: 'Team development: stages and workflow', intro: 'Tuckman describes relationship maturity; the Z-Process describes how an idea matures through different roles. Neither is a one-way line.', stages: [['Forming', 'Members meet; roles and goals remain unclear, so they rely on leader guidance.', 'Clarify goals and roles; establish the team charter.'], ['Storming', 'Members test boundaries and conflict over work practices, authority, or allocation.', 'Address conflict early and keep discussion safe and inclusive.'], ['Norming', 'Differences are resolved; members value strengths, trust grows, and feedback increases.', 'Build connections, feedback, and individual responsibility.'], ['Performing', 'High trust, low supervision, and flexible roles support efficient delivery.', 'Delegate, develop members, and watch for regression.'], ['Adjourning', 'The project ends or the team dissolves, creating loss and uncertainty.', 'Celebrate achievements, give feedback, and support next steps.']], nonLinear: 'Tuckman is not a one-way staircase. New members, changed direction, or pressure can move a team back to an earlier stage.', zTitle: 'Z-Process: mature the idea', roles: [['C', 'Creator', 'Creates the vision and new possibilities.'], ['A', 'Advancer', 'Connects with customers or users to gain feedback and test acceptance.'], ['R', 'Refiner', 'Researches, critiques, finds flaws, and develops a prototype.'], ['E', 'Executor', 'Turns a mature proposal into reality and manages implementation.']], risk: 'Creator → Refiner skips user feedback; Creator → Executor asks for implementation before validation and refinement. The process may iterate, but roles should not be skipped arbitrarily.',
    },
    hats: {
      title: 'Six Thinking Hats: six lenses', intro: 'Each hat is a temporary mode of thought, not a fixed personality. Parallel thinking means everyone wears the same hat at the same time.', items: [['White · Facts', 'Known data, available information, and gaps; remain neutral.', 'What do we know?', '#f7f5ed'], ['Red · Feelings', 'Emotion, intuition, and gut reaction without required justification.', 'How do we feel?', '#dc554e'], ['Black · Risks', 'Constraints, errors, obstacles, and worst cases.', 'What could go wrong?', '#242836'], ['Yellow · Benefits', 'Strengths, value, feasibility, and reasons for success.', 'What value can this create?', '#e4bc3b'], ['Green · Ideas', 'Creativity, alternatives, and provocation without early judgement.', 'What else could we try?', '#54a767'], ['Blue · Process', 'Goals, sequence, time, summary, and next steps.', 'How will we think and decide?', '#4c79c6']], sequence: 'Blue → White → Red → Green → Yellow → Black → Blue', sequenceNote: 'The sequence can change by task, but Blue commonly opens the process and closes by recording decisions and actions.', trap: 'Do not label people as a “black-hat person,” switch hats chaotically, let Black suppress Green too early, or forget Blue process management.',
    },
    communication: {
      title: 'Professional communication: Email + Questioning + I-statements', intro: 'All three reduce misunderstanding and defensiveness: email provides structure and context, questions improve feedback, and I-statements own feelings while making a request.', email: ['Use a clear, specific subject that matches the content.', 'Use an appropriate salutation; be concise but provide needed context.', 'Proofread and adapt formality and tone to culture and audience.', 'Use emoji, exclamation marks, humour, slang, and “urgent” carefully.', 'CC exposes addresses; BCC hides them and protects privacy in bulk mail.', 'Keep attachments reasonable and state the next step and deadline.', 'Usually respond within 24 hours or state when a response will come; use a professional signature.'], formula: 'I feel + when (event/problem) + I would like (request/solution)', iNote: 'Improves assertiveness without direct blame, lowers defensiveness, and supports empathy, cooperation, and conflict resolution.', bad: 'Pseudo I-statement: “I feel like you don’t care.” It begins with I but still judges the other person.', good: 'Better: “I feel worried when I don’t receive an update. I’d like us to agree on a check-in time.”', questions: [['Open · Explore', 'What aspects of our current design should we improve?', 'Use at the opening to gather detail beyond yes/no.'], ['Reflective · Clarify', 'It sounds like you’re concerned about the scope—is that right?', 'Use mid-conversation to reflect meaning, check understanding, and invite more detail.'], ['Closed · Confirm', 'Should we complete the prototype before Friday?', 'Use at the close to confirm facts, choices, commitments, deadlines, and next steps.']], tableHeaders: ['Concept', 'Focus', 'It is not'], tableRows: [['Social Contract', 'Shared behaviour and collaboration norms', 'A management order or unchangeable policy'], ['I-statement', 'My genuine feeling, triggering event, and desired change', 'A judgement disguised with “I feel”'], ['Effective questioning', 'Match the question to the meeting stage and feedback needed', 'Only open questions or leading questions throughout'], ['Professional email', 'Clear, respectful, and adapted to audience and culture', 'Always more formal; always CC everyone']],
    },
    quiz: {
      title: 'Quiz Ready: likely question patterns', intro: 'Prioritise sequences, mappings, distinctions, and contextual application. Select a question to reveal the answer.', items: [['Which statement is not a correct Social Contract feature?', '“It can override organisational policy” is wrong. The whole team creates and revises it, but it cannot override policy.'], ['Why does an absent member weaken a Social Contract?', 'Participation creates ownership, commitment, and accountability; someone excluded from creation is less likely to identify with it.'], ['Members challenge boundaries, leadership, and task allocation. Which stage is this?', 'Storming. Clarify roles, address conflict early, and protect open discussion.'], ['Can a Performing team return to an earlier stage?', 'Yes. New members, changing goals, or environmental pressure can disrupt group dynamics.'], ['Give the complete Tuckman sequence.', 'Forming → Storming → Norming → Performing → Adjourning (also called Mourning).'], ['What is the Z-Process role sequence?', 'Creator → Advancer → Refiner → Executor—CARE.'], ['What is the risk when a Creator hands an idea directly to an Executor?', 'The idea lacks user feedback, critical analysis, and prototyping, leaving the Executor with ambiguous, unvalidated requirements.'], ['Which hats represent facts, feelings, risks, benefits, ideas, and process?', 'White, Red, Black, Yellow, Green, and Blue.'], ['Why is Blue Hat often used at the beginning and end?', 'It opens by defining the problem, goal, rules, and sequence; it closes by summarising, recording decisions, and setting next steps.'], ['What distinguishes parallel thinking from ordinary debate?', 'Everyone uses the same perspective at the same time; hats are temporary lenses, not personality labels.'], ['Why is “I feel like you are careless” a poor I-statement?', 'It judges the other person instead of describing a genuine feeling, triggering defensiveness. State the feeling, event, and request.'], ['How do CC and BCC differ, and what else should email make clear?', 'CC recipients are visible; BCC hides addresses. Also clarify subject, tone, context, action/deadline, and signature.'], ['When should Open, Reflective, and Closed questions be used with a mentor?', 'Open at the start to explore; Reflective in the middle to clarify; Closed at the end to confirm commitment: Explore → Clarify → Confirm.']], memory: [['FSNPA', 'Forming → Storming → Norming → Performing → Adjourning'], ['CARE', 'Creator → Advancer → Refiner → Executor'], ['W R B Y G B', 'Facts · Feelings · Risks · Benefits · Ideas · Process'], ['Open → Reflective → Closed', 'Explore → Clarify → Confirm'], ['Feel → Event → Request', 'I feel… when… I would like…']],
    },
    sources: ['Agile Ways of Working — Social Contracts', 'Social Contracts for Agile Teams', 'Forming, Storming, Norming, and Performing', 'The Happy Manager — Teamwork Theory', 'Using the Z-Process to Develop an Effective Team Workflow', 'Six Thinking Hats Technique by Edward de Bono', '15 Email Etiquette Rules for Every Professional', 'How Using I Feel Statements Can Help You Communicate', 'Euson — Listening, Questioning and Feedback'],
  },
} as const

export default function Week02({ locale }: { locale: Locale }) {
  const c = copy[locale]
  const { t } = useTranslation()
  const ids = ['overview', 'contract', 'development', 'hats', 'communication', 'quiz', 'sources']
  const toc = ids.map((id, index) => ({ id, label: c.toc[index] }))

  return (
    <WeekLayout weekId="02" locale={locale} eyebrow="Week 02 · Study brief" title={c.title} subtitle={c.subtitle} summary={c.summary} updated="04 Sep 2026" tags={[...c.tags]} toc={toc}>
      <ContentSection id="overview" index="01" title={c.overview.title} intro={c.overview.intro}>
        <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{c.overview.cards.map(([title, body], index) => <InfoCard key={title} title={`${String(index + 1).padStart(2, '0')} · ${title}`} tone={index % 2 ? 'plain' : 'accent'}>{body}</InfoCard>)}</div>
      </ContentSection>
      <ContentSection id="contract" index="02" title={c.contract.title} intro={c.contract.intro}>
        <LeadCard label={locale === 'zh' ? '核心定义' : 'Core definition'}>{c.contract.definition}</LeadCard>
        <div className="mt-4 grid gap-4 md:grid-cols-2"><InfoCard title={locale === 'zh' ? '关键原则' : 'Key principles'} tone="accent"><ul className="list-disc space-y-2 pl-5">{c.contract.principles.map((item) => <li key={item}>{item}</li>)}</ul></InfoCard><InfoCard title={locale === 'zh' ? '创建流程' : 'Creation process'}><ol className="list-decimal space-y-2 pl-5">{c.contract.process.map((item) => <li key={item}>{item}</li>)}</ol></InfoCard></div>
        <Callout label="Quiz clue">{c.contract.clue}</Callout><div className="mt-4"><ResponsiveTable headers={[...c.contract.tableHeaders]} rows={c.contract.tableRows.map((row) => [...row])} /></div>
      </ContentSection>
      <ContentSection id="development" index="03" title={c.development.title} intro={c.development.intro}>
        <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-5">{c.development.stages.map(([name, body, action], index) => <InfoCard key={name} title={`${index + 1}. ${name}`} tone={index === 1 ? 'coral' : index === 3 ? 'accent' : 'plain'}><p>{body}</p><p className="mt-3 font-semibold text-foreground">Leader: {action}</p></InfoCard>)}</div>
        <Callout label={locale === 'zh' ? '易考判断' : 'Exam clue'}>{c.development.nonLinear}</Callout><h3 className="mb-4 mt-10 text-2xl font-black tracking-tight">{c.development.zTitle}</h3>
        <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{c.development.roles.map(([letter, name, body]) => <InfoCard key={letter} title={`${letter} · ${name}`} tone="accent">{body}</InfoCard>)}</div><Callout label="Short-circuit risk">{c.development.risk}</Callout>
      </ContentSection>
      <ContentSection id="hats" index="04" title={c.hats.title} intro={c.hats.intro}>
        <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{c.hats.items.map(([name, body, question, color]) => <div key={name} data-print-break-inside className="rounded-2xl border bg-card p-6 shadow-sm"><div className="flex items-center gap-3"><span className="size-4 rounded-full border shadow-sm" style={{ backgroundColor: color }} /><h3 className="font-black">{name}</h3></div><p className="mt-3 text-sm leading-7 text-muted-foreground">{body}</p><p className="mt-4 text-xs font-bold text-foreground">{question}</p></div>)}</div>
        <div className="mt-4"><LeadCard label={locale === 'zh' ? '常见完整顺序' : 'Common full sequence'} note={c.hats.sequenceNote}>{c.hats.sequence}</LeadCard></div><Callout label={locale === 'zh' ? '常见陷阱' : 'Common trap'}>{c.hats.trap}</Callout>
      </ContentSection>
      <ContentSection id="communication" index="05" title={c.communication.title} intro={c.communication.intro}>
        <div className="grid gap-4 lg:grid-cols-2"><InfoCard title="Email etiquette"><ul className="list-disc space-y-2 pl-5">{c.communication.email.map((item) => <li key={item}>{item}</li>)}</ul></InfoCard><InfoCard title="I-statements" tone="accent"><p className="text-lg font-black text-foreground">{c.communication.formula}</p><p className="mt-3">{c.communication.iNote}</p><p className="mt-4 rounded-xl bg-white/55 p-3">{c.communication.bad}</p><p className="mt-2 rounded-xl bg-white/70 p-3 font-semibold text-foreground">{c.communication.good}</p></InfoCard></div>
        <h3 className="mb-4 mt-8 text-2xl font-black">Effective Questioning · Explore → Clarify → Confirm</h3><div className="grid gap-3 lg:grid-cols-3">{c.communication.questions.map(([kind, example, use], index) => <InfoCard key={kind} title={kind} tone={index === 0 ? 'blue' : index === 1 ? 'warm' : 'accent'}><p className="font-semibold text-foreground">“{example}”</p><p className="mt-2">{use}</p></InfoCard>)}</div><div className="mt-4"><ResponsiveTable headers={[...c.communication.tableHeaders]} rows={c.communication.tableRows.map((row) => [...row])} /></div>
      </ContentSection>
      <ContentSection id="quiz" index="06" title={c.quiz.title} intro={c.quiz.intro}><QuizAccordion items={c.quiz.items.map(([question, answer]) => ({ question, answer }))} /><div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{c.quiz.memory.map(([key, value]) => <InfoCard key={key} title={key} tone="accent">{value}</InfoCard>)}</div></ContentSection>
      <ContentSection id="sources" index="07" title={locale === 'zh' ? '资料来源' : 'Sources'}><SourceList items={[...c.sources]} note={t('sourceNote')} /></ContentSection>
    </WeekLayout>
  )
}
