import { ExternalLink } from 'lucide-react'
import { QuizAccordion } from '@/components/quiz-accordion'
import { Callout, ContentSection, InfoCard, LeadCard, ResponsiveTable, WeekLayout } from '@/components/week-layout'
import qualityVisual from '@/assets/week06-quality.png'
import type { Locale } from '@/i18n'

const sources = [
  ['Quality Measurement and Management visual', 'Course visual', null],
  ['Measuring and Managing Quality', 'Course video · 14:11', null],
  ['Code Quality Podcast', 'Course audio · 05:40', null],
  ['What Determines Software Quality?', 'Target page replaced; source status recorded', 'https://www.buildingbettersoftware.com/the-impact-of-poor-software-quality/'],
  ['The $2t Cost of Poor Software Quality', 'CISQ costs, supply chain, technical debt', 'https://istart.com.au/news-items/the-2t-cost-of-poor-software-quality/'],
  ['What Happens When Testing Goes Wrong?', 'Reputation, revenue, feedback, litigation', 'https://muuktest.com/blog/impact-of-poor-software-quality/'],
  ['Improve Software Testing', 'Eleven testing and QA practices', 'https://www.altexsoft.com/blog/engineering/software-testing-qa-best-practices/'],
  ["Software Quality Management Best Practices", "Five do's and don'ts", 'https://katalon.com/resources-center/blog/software-quality-management-best-practices'],
  ['Software Quality Standards — ISO 5055', 'Automated structural source-code quality', 'https://www.it-cisq.org/standards/code-quality-standards/'],
  ['ISO/IEC 9126 in Software Engineering', 'Product-quality model and metrics', 'https://www.geeksforgeeks.org/software-engineering/iso-iec-9126-in-software-engineering/'],
  ['Purpose of ISO 27001', 'ISMS, CIA, implementation, controls', 'https://www.globalsuitesolutions.com/what-is-the-iso-27001-standard-and-what-is-its-purpose/'],
] as const

const copy = {
  zh: {
    title: 'Software Quality', subtitle: '衡量质量，管理可靠性',
    summary: '软件质量不是发布前“测出来”的标签，而是从需求、设计、开发、验证到运行持续构建的系统能力。',
    tags: ['11 份 own-time 材料', '3 套 ISO 标准', '8 道自测', '全生命周期质量'],
    toc: ['核心概念', '质量度量', '标准地图', '管理与测试', '风险与成本', 'Do / Don’t', '项目落地', '速记自测', '材料索引'],
    foundation: {
      title: '先定义，后谈质量', intro: '质量不是抽象的“好”，而是产品满足需求、用户目标与风险约束的程度。', lead: 'Defect = 行为不符合需求；Quality = 产品在特定情境下适合其目的。',
      leadNote: '缺陷具有情境性：桌面专用产品的移动显示问题未必违反当前需求；目标用户需要移动使用时，它就成为质量问题。',
      triad: [['Quality Assurance · SQA', '组织与流程导向，通过规范、计划、角色和预防活动减少错误产生。'], ['Quality Control · SQC', '产品与结果导向，检查交付物在发布前是否满足质量要求。'], ['Testing', '发现技术问题，并评估功能、可用性、性能、安全性与兼容性。']],
      distinction: '测试告诉团队哪里已有问题；质量保证关注如何让问题更少发生。高质量来自完整生命周期。',
      defectHeaders: ['概念', '判断问题', '管理含义'], defectRows: [['Severity 严重度', '影响有多大？', '反映技术或业务后果；Sev 1 常指系统不可用且无 workaround。'], ['Priority 优先级', '多快需要处理？', '综合严重度、紧迫性、用户可见性与业务时机。'], ['Acceptable defects', '剩余风险可接受吗？', '普通系统可权衡；关键系统应把可接受缺陷趋近于零。']],
      target: 'Six Sigma 以约 3.4 defects per million opportunities 表示低缺陷目标；Crosby 的 Zero Defects 强调不要把缺陷视为必然。',
      system: '故障可能来自人、流程或技术。有效改进必须定位系统原因，而不是只补表面 bug。',
      critical: [['Safety-critical', '失败可能导致死亡、重伤、重大财产或环境损害。'], ['Mission-critical', '失败显著中断核心运营，甚至威胁组织生存。'], ['Business-critical', '失败造成极高业务成本，例如银行核心服务中断。']],
    },
    measurement: {
      title: '把“好”变成可衡量', intro: '单看缺陷数不够。完整度量同时覆盖内部结构、外部行为和用户真实结果。', layers: [['Internal quality', '不运行软件也可观察的结构属性：架构弱点、复杂度、可维护性与静态分析发现。'], ['External quality', '运行时行为：错误、响应时间、资源使用、恢复能力与兼容性。'], ['Quality in use', '用户结果：有效性、生产力、安全和满意度，最终回答是否适合目的。']],
      pillars: [['Functionality 功能性', '适合、准确、互操作、安全'], ['Reliability 可靠性', '成熟、容错、恢复'], ['Usability 易用性', '理解、学习、操作'], ['Efficiency 效率', '时间行为、资源利用'], ['Maintainability 可维护性', '分析、修改、稳定、测试'], ['Portability 可移植性', '适应、安装、共存、替换']],
      metricHeaders: ['质量维度', '要回答的问题', '材料中的指标 / 方法'], metricRows: [['Defects', '偏离需求的问题有多少、影响多大？', '缺陷数量、严重度、优先级、生产缺陷'], ['Reliability', '能稳定运行多久？变更是否破坏原功能？', '负载、回归、宕机与生产缺陷'], ['Performance efficiency', '给定时间与资源下是否响应？', '压力、浸泡测试、APM'], ['Security', '能否抵御未授权访问和漏洞？', '漏洞数、补丁部署率、解决时间'], ['Maintainability', '修改、理解、交接是否容易？', '代码行数、圈复杂度、ISO 5055 弱点'], ['Delivery', '能否持续安全交付价值？', '发布频率与反馈速度']],
      principle: '指标必须连接需求、风险与决策。先问它会改变什么行动，再决定是否收集。',
    },
    standards: {
      title: '三套标准，各管一层', intro: '把标准看成互补视角：产品质量模型、源代码结构测量、组织级信息安全管理。', items: [['ISO/IEC 9126', '产品质量模型', '质量模型、外部指标、内部指标、使用质量；六项产品特征，2011 年由 ISO/IEC 25010 取代。'], ['ISO/IEC 5055', '源代码结构 · 2021', '静态分析可靠性、安全性、性能效率和可维护性，在事故前发现架构与组件弱点。'], ['ISO/IEC 27001', 'ISMS · 持续改进', '建立信息安全管理体系，保护 Confidentiality、Integrity、Availability。']],
      headers: ['标准', '主要对象', '核心用途', '典型产出'], rows: [['9126 / 25010', '软件产品与使用结果', '定义质量维度与评价模型', '质量属性、子属性、内部/外部/使用指标'], ['5055', '源代码内部结构', '事故前自动发现危险弱点', '弱点计数/密度、发布与供应商门槛'], ['27001', '组织的 ISMS', '风险驱动的政策、控制、审计和改进', '范围、风险处理、控制、内审与管理评审']],
      iso5055: '像检查房屋内部结构，发现 SQL 注入、资源未释放、绕过认证路径等问题；可写进合同、发布条件和技术债目标。',
      iso27001: 'Plan 识别范围与风险；Do 实施政策和控制；Check 监控与审计；Act 纠正并持续改进。2022 Annex A 有 93 项控制，分组织、人员、物理、技术四组。',
    },
    management: {
      title: '质量要贯穿生命周期', intro: 'Shift-left 不是机械地把所有测试前移，而是让反馈、质疑与风险判断更早出现。', flow: [['Require', '澄清用户、问题、环境、指标、负载、安全与更新。'], ['Design', '原型、多方案、评审和可用性测试。'], ['Build', 'TDD、结对、可测试代码、静态分析、小步集成。'], ['Verify', '单元、集成、E2E、探索测试、FTR 与 UAT。'], ['Learn', '监控真实表现、用户反馈、缺陷、补丁和技术债。']],
      pyramid: [['E2E / UI', '少量 · 慢 · 贵'], ['Integration', '验证服务、数据库和文件系统协作'], ['Unit tests', '大量 · 快 · 高频反馈']],
      strategy: [['TDD · Red → Green → Refactor', '先写失败测试，再写最少实现，最后重构并保持测试通过。'], ['Formal Technical Review', '正式评审、walkthrough 或 inspection 尽早发现偏差并记录决定。'], ['User Acceptance Testing', '领域专家和用户验证合同、法规、运营与真实使用需求。'], ['CI / CD', '每次变更自动测试，只有通过门槛的变更进入发布。'], ['Exploratory / Ad hoc', '人工创造力发现脚本未覆盖的未知风险与异常行为。'], ['Effective bug report', '一单一问题，写清环境、复现、实际/预期结果与证据。']],
      vmodel: '越靠前的错误越昂贵。Agile 不会消除这个规律；每次迭代都应重新验证问题陈述、用户故事和设计假设。',
      podcast: 'Podcast 把代码弱点比作大楼墙内漏水：只数外部“水渍”不够，必须用圈复杂度与结构分析及早发现内部腐朽；质量管理的最终目标是保护 ideas → production 的 flow。',
      aiQuestion: '当 AI 能在数秒内生成代码时，缺陷也会以更高速度进入系统。可接受缺陷不能因此放宽；自动生成必须配套自动测试、结构分析、人工判断和清晰责任。',
    },
    impact: {
      title: '低质量不是“小 bug”', intro: '它沿技术、运营、客户与法律链路放大，并通过技术债把今天的速度转化为明天的阻力。', stats: [['US$2.4T', '2022 年美国低质量软件估算总成本'], ['US$1.8T', '运营系统软件失败估算成本'], ['13.5h', '开发者每 41.1 小时处理技术债'], ['+650%', '开源供应链弱点相关问题增长']],
      caution: '这些是 CISQ / Synopsys 估算，用来显示数量级与风险结构；类别可能交叉，不能简单相加。', chain: ['需求误解', '浅层 / 延迟测试', '生产缺陷', '宕机 / 泄露 / 数据丢失', '收入与声誉损失', '监管与诉讼'],
      consequences: [['Reputation', '糟糕体验迅速转化为商店评分和社交口碑。'], ['Revenue & technical debt', '省略测试换来短期速度，却增加维护与现代化失败风险。'], ['Legal & social impact', '可访问性、安全、隐私、数据丢失与宕机可能引发处罚或诉讼。'], ['SBOM', '掌握第三方与开源组件，漏洞出现时快速定位与修补。'], ['DevQualOps', '为 Agile/DevOps 高速交付加入质量活动、门槛、分析和监控。']],
    },
    practice: {
      title: '把原则变成团队行为', intro: '有效质量管理不是购买更多工具，而是让人员、流程、技术和决策方式相互支持。', dos: ['先写可测试需求与代码，适合时采用 TDD。', '自动化回归、冒烟、负载和跨环境重复测试。', '用云测试环境扩大浏览器、设备和操作系统覆盖。', '在有价值处使用低代码并复用测试资产。', '制定测试策略并遵循分层投资。', '让开发、QA、用户和业务共同负责。'], donts: ['没有工程反馈就改变范围与期限。', '把 bug 归咎个人，忽略需求、流程和复杂性。', '只因工具免费或流行就采用。', '隔离开发与 QA，最后才移交测试。', '把自动化与人工测试二选一。', '让测试数据散落在互不连通的工具中。'],
      docs: 'Test policy 定义组织原则；quality management plan 定义项目目标与责任；test strategy 定义产品级方法；test plan 说明测什么、何时、如何、由谁执行。', environment: '明确角色、尊重测试人员、提供业务训练、鼓励开发与 QA 直接沟通，并用 retrospective 改善协作。', tools: '连接需求、用例、环境、结果、缺陷与 KPI；工具服务流程，而不是替代思考。',
    },
    project: { title: '用于 IE / 团队项目', intro: '把 Week 06 转换成一份现在就能执行的质量路线图。', phases: [['Discover', '定义 fit for purpose', ['目标用户与客户需求是否冲突？', '产品解决什么问题，成功指标是什么？', '用户何时、何地、用什么设备？', '失败属于何种关键等级？']], ['Design', '实现前发现错误', ['写清用户故事和验收标准。', '用原型与多方案验证关键流程。', '邀请真实用户做可用性测试。', '明确负载、授权、攻击与更新策略。']], ['Build', '建立持续反馈', ['单元测试打底，补关键集成与 E2E。', 'CI 中运行回归与静态分析。', '结对或评审高风险变更。', '记录依赖并维护 SBOM。']], ['Validate', '以证据决定发布', ['按 severity × priority 整理缺陷。', '让用户执行关键任务并提供 UAT 证据。', '测试文档、培训与恢复。', '同步指标、剩余风险与发布建议。']]] },
    review: {
      title: '三组速记 + 八题自测', intro: '先记结构，再补细节。点击问题展开参考答案。', memory: [['3 × Quality', 'SQA 管过程与预防；SQC 管产品符合性；Testing 发现与评估问题。'], ['6 × ISO 9126', '功能、可靠、易用、效率、维护、移植。'], ['4 × ISO 5055', '可靠、安全、性能效率、可维护。']],
      quiz: [['为什么同一行为在一个项目中是缺陷、另一个不是？', '缺陷以需求和使用情境为参照；需求变化后判断也会变化。'], ['Severity 与 Priority 有何区别？', 'Severity 描述影响，Priority 描述处理紧迫性。'], ['为什么增加测试不能单独保证质量？', '测试主要暴露已有问题；错误需求、设计和流程必须更早预防。'], ['三套 ISO 标准分别解决什么？', '9126 是产品质量模型；5055 测源代码结构；27001 建组织 ISMS。'], ['Shift-left 的核心是什么？', '让评审、风险识别、测试设计、自动反馈和协作更早发生。'], ['为什么大量单元测试、少量 E2E？', '单元测试快、稳定、便宜；E2E 慢、贵且更易 flaky。'], ['为什么安全是可靠性的一部分？', '攻击和漏洞会导致不可用、数据破坏或错误行为。'], ['低质量成本为何持续累积？', '直接损失之外，技术债还降低变更速度并提高回归风险。']],
    },
    sourcesTitle: 'Own-time 材料索引', sourcesIntro: '公开文章可回到原站核对；课程视觉与音视频只用于本页总结，不公开转录文件。', boundary: '“What Determines Software Quality?” 的目标网页已被无关内容替换。本页没有采用替换后的文章。',
  },
  en: {
    title: 'Software Quality', subtitle: 'Measure quality. Manage reliability.', summary: 'Software quality is not a label that can be tested in before release. It is a system capability built continuously across requirements, design, development, verification, and operation.', tags: ['11 own-time materials', '3 ISO standards', '8 self-checks', 'Lifecycle quality'], toc: ['Foundations', 'Measurement', 'Standards', 'Management & testing', 'Risk & cost', 'Do / Don’t', 'Project application', 'Review', 'Sources'],
    foundation: { title: 'Define quality before judging it', intro: 'Quality is not an abstract sense of good; it is the extent to which a product satisfies requirements, user goals, and risk constraints.', lead: 'Defect = behaviour that does not conform to requirements; Quality = fitness for purpose in a specific context.', leadNote: 'Defects are contextual. Poor mobile rendering may not violate a desktop-only requirement, but becomes a quality issue when target users need mobile access.', triad: [['Quality Assurance · SQA', 'Organisation- and process-oriented standards, plans, roles, and prevention.'], ['Quality Control · SQC', 'Product- and outcome-oriented inspection before release.'], ['Testing', 'Finds issues and evaluates function, usability, performance, security, and compatibility.']], distinction: 'Testing shows where problems already exist; assurance focuses on preventing them. Quality comes from the full lifecycle.', defectHeaders: ['Concept', 'Question', 'Management meaning'], defectRows: [['Severity', 'How large is the impact?', 'Technical or business consequence; Sev 1 often means unavailable with no workaround.'], ['Priority', 'How quickly should it be handled?', 'Combines severity, urgency, visibility, and business timing.'], ['Acceptable defects', 'Is residual risk acceptable?', 'Ordinary systems can trade off risk; critical systems drive defects towards zero.']], target: 'Six Sigma illustrates a low-defect target near 3.4 defects per million opportunities; Crosby’s Zero Defects says defects should not be treated as inevitable.', system: 'Failures may come from people, process, or technology. Improvement must address systemic causes, not just surface bugs.', critical: [['Safety-critical', 'Failure may cause death, serious injury, major property, or environmental harm.'], ['Mission-critical', 'Failure significantly interrupts core operation and may threaten survival.'], ['Business-critical', 'Failure imposes very high business costs, such as core banking interruption.']] },
    measurement: { title: 'Make good measurable', intro: 'Defect counts alone are insufficient. Complete measurement covers internal structure, external behaviour, and real user outcomes.', layers: [['Internal quality', 'Structure observable without running software: architecture, complexity, maintainability, static analysis.'], ['External quality', 'Runtime behaviour: errors, response time, resources, recovery, and compatibility.'], ['Quality in use', 'User outcomes: effectiveness, productivity, safety, and satisfaction—fitness for purpose.']], pillars: [['Functionality', 'Suitability, accuracy, interoperability, security'], ['Reliability', 'Maturity, fault tolerance, recovery'], ['Usability', 'Understand, learn, operate'], ['Efficiency', 'Time behaviour, resources'], ['Maintainability', 'Analyse, change, stabilise, test'], ['Portability', 'Adapt, install, coexist, replace']], metricHeaders: ['Dimension', 'Question', 'Measures / methods'], metricRows: [['Defects', 'How many deviations and how much impact?', 'Count, severity, priority, production defects'], ['Reliability', 'How long stable? Do changes break behaviour?', 'Load, regression, downtime, production defects'], ['Performance efficiency', 'Responsive within time and resources?', 'Stress, soak, APM'], ['Security', 'Resist unauthorised access and exploitation?', 'Vulnerabilities, patch rate, resolution time'], ['Maintainability', 'Easy to modify, understand, and hand over?', 'LOC, cyclomatic complexity, ISO 5055 weaknesses'], ['Delivery', 'Deliver value continuously and safely?', 'Release frequency and feedback speed']], principle: 'Measures must connect to requirements, risk, and decisions. Ask what action a metric changes before collecting it.' },
    standards: { title: 'Three standards, three layers', intro: 'Complementary views: product-quality model, source-code structural measurement, and organisational information-security management.', items: [['ISO/IEC 9126', 'Product model', 'Quality model, external, internal, and in-use metrics; six product characteristics; replaced by ISO/IEC 25010 in 2011.'], ['ISO/IEC 5055', 'Source code · 2021', 'Static analysis of reliability, security, performance efficiency, and maintainability before incidents.'], ['ISO/IEC 27001', 'ISMS · continual', 'An information-security management system protecting confidentiality, integrity, and availability.']], headers: ['Standard', 'Primary object', 'Core purpose', 'Typical output'], rows: [['9126 / 25010', 'Product and outcomes in use', 'Define dimensions and evaluation model', 'Characteristics and internal/external/in-use measures'], ['5055', 'Internal source structure', 'Find dangerous weaknesses before incidents', 'Counts/density, release and supplier gates'], ['27001', 'Organisation ISMS', 'Risk-based policy, control, audit, improvement', 'Scope, treatment, control, audit, review']], iso5055: 'Like inspecting a building’s internal structure: find SQL injection, unreleased resources, and authentication bypasses; use measures in contracts, release gates, and debt targets.', iso27001: 'Plan scope and risk; Do policies and controls; Check through monitoring and audit; Act to correct and improve. The 2022 Annex A has 93 controls in four groups.' },
    management: { title: 'Build quality across the lifecycle', intro: 'Shift-left is not mechanically moving every test earlier; it brings feedback, questions, and risk judgement forward.', flow: [['Require', 'Clarify users, problems, environment, measures, load, security, and updates.'], ['Design', 'Prototype, compare alternatives, review, and test usability.'], ['Build', 'TDD, pairing, testable code, static analysis, small integrations.'], ['Verify', 'Unit, integration, E2E, exploration, FTR, and UAT.'], ['Learn', 'Monitor real performance, feedback, defects, patches, and debt.']], pyramid: [['E2E / UI', 'Few · slow · expensive'], ['Integration', 'Verify services, databases, and file systems'], ['Unit tests', 'Many · fast · frequent feedback']], strategy: [['TDD · Red → Green → Refactor', 'Write a failing test, implement the minimum, then refactor with tests green.'], ['Formal Technical Review', 'Review, walkthrough, or inspect early and record decisions.'], ['User Acceptance Testing', 'Domain experts and users validate contract, regulation, operation, and real use.'], ['CI / CD', 'Test every change; only changes through gates enter release.'], ['Exploratory / Ad hoc', 'Human creativity finds unknown risks beyond scripts.'], ['Effective bug report', 'One issue per ticket with context, reproduction, expected/actual, evidence.']], vmodel: 'Earlier errors cost more. Agile does not remove this: revalidate the problem, stories, and design every iteration.', podcast: 'The podcast compares code weakness to a leak inside a tower: counting visible stains is not enough. Cyclomatic complexity and structural analysis find internal decay early; quality management protects the flow from ideas to production.', aiQuestion: 'When AI generates code in seconds, defects can enter systems just as quickly. Acceptable quality must not loosen; generated code needs automated tests, structural analysis, human judgement, and clear accountability.' },
    impact: { title: 'Poor quality is not just a bug', intro: 'It amplifies through technical, operational, customer, and legal pathways while debt turns today’s speed into tomorrow’s resistance.', stats: [['US$2.4T', 'Estimated 2022 US cost of poor software quality'], ['US$1.8T', 'Estimated operational software failure cost'], ['13.5h', 'Developer time per 41.1 hours spent on debt'], ['+650%', 'Growth in open-source supply-chain weakness issues']], caution: 'These CISQ / Synopsys estimates show scale and risk structure; overlapping categories should not simply be added.', chain: ['Misunderstood requirements', 'Shallow / delayed testing', 'Production defects', 'Downtime / breach / data loss', 'Revenue and reputation loss', 'Regulation and litigation'], consequences: [['Reputation', 'Poor experience rapidly becomes store ratings and social sentiment.'], ['Revenue & technical debt', 'Skipping tests creates short-term speed but raises maintenance and modernisation risk.'], ['Legal & social impact', 'Accessibility, security, privacy, data loss, and downtime can trigger penalties.'], ['SBOM', 'Track third-party and open-source components to locate and patch new vulnerabilities.'], ['DevQualOps', 'Add quality activities, gates, analysis, and monitoring to high-velocity delivery.']] },
    practice: { title: 'Turn principles into team behaviour', intro: 'Effective quality management aligns people, process, technology, and decisions; it is not just more tools.', dos: ['Write testable requirements and code; use TDD where it fits.', 'Automate regression, smoke, load, and repeated cross-environment tests.', 'Use cloud environments for broad browser, device, and OS coverage.', 'Use low-code where valuable and reuse test assets.', 'Define a strategy and invest in testing layers.', 'Make development, QA, users, and business jointly responsible.'], donts: ['Change scope and deadlines without engineering input.', 'Blame individuals while ignoring requirements, process, and complexity.', 'Adopt tools only because they are free or popular.', 'Silo development and QA until final handover.', 'Treat manual and automated testing as a binary choice.', 'Scatter test data across disconnected tools.'], docs: 'Test policy defines organisational principles; quality management plan defines project goals and roles; test strategy defines the product approach; test plan states what, when, how, and who.', environment: 'Clarify roles, respect testers, provide business training, support direct development–QA communication, and improve through retrospectives.', tools: 'Connect requirements, cases, environments, results, defects, and KPIs. Tools serve process; they do not replace thinking.' },
    project: { title: 'Apply it to an IE / team project', intro: 'Turn Week 06 into a quality roadmap the team can use now.', phases: [['Discover', 'Define fit for purpose', ['Do client and user needs conflict?', 'What problem and success measure?', 'When, where, and on what device?', 'What criticality level?']], ['Design', 'Find errors before implementation', ['Write stories and acceptance criteria.', 'Prototype critical flows and alternatives.', 'Test usability with real users.', 'Define load, authorisation, attack, update.']], ['Build', 'Create continuous feedback', ['Unit base, then critical integration and E2E.', 'Regression and static analysis in CI.', 'Pair or review risky changes.', 'Record dependencies and maintain SBOM.']], ['Validate', 'Use evidence for release', ['Organise by severity × priority.', 'Collect UAT evidence on critical tasks.', 'Test documentation, training, recovery.', 'Share measures, residual risk, release advice.']]] },
    review: { title: 'Three memory aids + eight checks', intro: 'Remember the structure first, then add detail. Select a question to reveal its answer.', memory: [['3 × Quality', 'SQA manages process and prevention; SQC product conformity; testing finds and evaluates problems.'], ['6 × ISO 9126', 'Functionality, reliability, usability, efficiency, maintainability, portability.'], ['4 × ISO 5055', 'Reliability, security, performance efficiency, maintainability.']], quiz: [['Why can the same behaviour be a defect in one product but not another?', 'Defects are judged against requirements and context; changing requirements changes the judgement.'], ['How do severity and priority differ?', 'Severity describes impact; priority describes treatment urgency.'], ['Why can more testing not guarantee quality by itself?', 'Testing exposes existing problems; wrong requirements, design, and process require earlier prevention.'], ['What does each ISO standard address?', '9126 models product quality; 5055 measures source structure; 27001 establishes an organisational ISMS.'], ['What is the core of shift-left?', 'Bring review, risk identification, test design, automated feedback, and collaboration forward.'], ['Why many unit tests and few E2E tests?', 'Unit tests are fast, stable, and cheap; E2E tests are slow, expensive, and more flaky.'], ['Why is security part of reliability?', 'Attacks and vulnerabilities cause unavailability, data damage, and incorrect behaviour.'], ['Why does poor-quality cost accumulate?', 'Beyond direct loss, debt slows future change and raises regression risk.']] },
    sourcesTitle: 'Own-time material index', sourcesIntro: 'Public articles link to their original sites; course visuals and audio/video are summarised here without publishing transcript files.', boundary: 'The target for “What Determines Software Quality?” was replaced by unrelated content, which is not used in this guide.',
  },
} as const

export default function Week06({ locale }: { locale: Locale }) {
  const c = copy[locale]
  const ids = ['foundation', 'measurement', 'standards', 'management', 'impact', 'practice', 'project', 'review', 'sources']
  const toc = ids.map((id, index) => ({ id, label: c.toc[index] }))
  return (
    <WeekLayout weekId="06" locale={locale} eyebrow="Week 06 · Own-time knowledge summary" title={c.title} subtitle={c.subtitle} summary={c.summary} updated="04 Sep 2026" tags={[...c.tags]} toc={toc}>
      <ContentSection id="foundation" index="01" title={c.foundation.title} intro={c.foundation.intro}><LeadCard label={locale === 'zh' ? '核心定义' : 'Core definition'} note={c.foundation.leadNote}>{c.foundation.lead}</LeadCard><div className="mt-4 grid gap-3 md:grid-cols-3">{c.foundation.triad.map(([title, body]) => <InfoCard key={title} title={title} tone="accent">{body}</InfoCard>)}</div><Callout label={locale === 'zh' ? '关键辨析' : 'Key distinction'}>{c.foundation.distinction}</Callout><div className="mt-4"><ResponsiveTable headers={[...c.foundation.defectHeaders]} rows={c.foundation.defectRows.map((row) => [...row])} /></div><div className="mt-4 grid gap-4 md:grid-cols-2"><InfoCard title="Six Sigma → Zero Defects">{c.foundation.target}</InfoCard><InfoCard title="Whole-system view" tone="accent">{c.foundation.system}</InfoCard></div><div className="mt-4 grid gap-3 md:grid-cols-3">{c.foundation.critical.map(([title, body], index) => <InfoCard key={title} title={title} tone={index === 0 ? 'coral' : index === 1 ? 'warm' : 'blue'}>{body}</InfoCard>)}</div></ContentSection>
      <ContentSection id="measurement" index="02" title={c.measurement.title} intro={c.measurement.intro}><div className="grid gap-3 md:grid-cols-3">{c.measurement.layers.map(([title, body]) => <InfoCard key={title} title={title} tone="accent">{body}</InfoCard>)}</div><div className="mt-4 grid grid-cols-2 gap-2 lg:grid-cols-6">{c.measurement.pillars.map(([title, body]) => <div key={title} className="rounded-2xl bg-primary p-4 text-primary-foreground"><h3 className="text-sm font-black">{title}</h3><p className="mt-3 text-xs leading-5 text-white/65">{body}</p></div>)}</div><div className="mt-4"><ResponsiveTable headers={[...c.measurement.metricHeaders]} rows={c.measurement.metricRows.map((row) => [...row])} /></div><Callout label={locale === 'zh' ? '指标原则' : 'Measurement principle'}>{c.measurement.principle}</Callout></ContentSection>
      <ContentSection id="standards" index="03" title={c.standards.title} intro={c.standards.intro}><div className="grid gap-4 md:grid-cols-3">{c.standards.items.map(([title, label, body], index) => <InfoCard key={title} title={title} tone={index === 1 ? 'accent' : index === 2 ? 'warm' : 'plain'}><p className="mb-3 text-xs font-black uppercase tracking-wider text-foreground">{label}</p>{body}</InfoCard>)}</div><div className="mt-4"><ResponsiveTable headers={[...c.standards.headers]} rows={c.standards.rows.map((row) => [...row])} /></div><div className="mt-4 grid gap-4 md:grid-cols-2"><InfoCard title="ISO 5055" tone="accent">{c.standards.iso5055}</InfoCard><InfoCard title="ISO 27001 · PDCA" tone="warm">{c.standards.iso27001}</InfoCard></div></ContentSection>
      <ContentSection id="management" index="04" title={c.management.title} intro={c.management.intro}><div className="grid gap-2 md:grid-cols-3 lg:grid-cols-5">{c.management.flow.map(([title, body], index) => <InfoCard key={title} title={`${index + 1} · ${title}`}>{body}</InfoCard>)}</div><div className="mt-5 rounded-3xl border bg-card p-6"><h3 className="mb-4 text-xl font-black">Strategic testing pyramid</h3><div className="mx-auto flex max-w-2xl flex-col items-center gap-2">{c.management.pyramid.map(([title, body], index) => <div key={title} className="grid min-h-16 place-items-center rounded-xl px-4 text-center font-black text-white" style={{ width: `${50 + index * 25}%`, backgroundColor: index === 0 ? '#e2674a' : index === 1 ? '#e9a23b' : '#0b766b' }}><span>{title}<small className="block font-medium opacity-75">{body}</small></span></div>)}</div></div><div className="mt-4 grid gap-3 md:grid-cols-2 lg:grid-cols-3">{c.management.strategy.map(([title, body]) => <InfoCard key={title} title={title} tone="accent">{body}</InfoCard>)}</div><Callout label="V-model">{c.management.vmodel}</Callout><div className="mt-4 grid gap-4 md:grid-cols-2"><InfoCard title={locale === 'zh' ? 'Podcast · 保护 flow' : 'Podcast · Protect the flow'} tone="blue">{c.management.podcast}</InfoCard><InfoCard title={locale === 'zh' ? 'AI 生成代码的新问题' : 'The AI-generated code question'} tone="coral">{c.management.aiQuestion}</InfoCard></div></ContentSection>
      <ContentSection id="impact" index="05" title={c.impact.title} intro={c.impact.intro}><div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{c.impact.stats.map(([value, label], index) => <InfoCard key={value} title={value} tone={index < 2 ? 'accent' : index === 2 ? 'warm' : 'coral'}>{label}</InfoCard>)}</div><Callout label={locale === 'zh' ? '数字边界' : 'Data boundary'}>{c.impact.caution}</Callout><div className="mt-4 flex flex-wrap items-center gap-2 rounded-2xl border bg-card p-5">{c.impact.chain.map((item, index) => <span key={item} className="contents"><span className="rounded-full bg-[#f8ddd5] px-3 py-2 text-xs font-bold">{item}</span>{index < c.impact.chain.length - 1 ? <b className="text-[#e2674a]">→</b> : null}</span>)}</div><div className="mt-4 grid gap-3 md:grid-cols-2 lg:grid-cols-3">{c.impact.consequences.map(([title, body]) => <InfoCard key={title} title={title}>{body}</InfoCard>)}</div></ContentSection>
      <ContentSection id="practice" index="06" title={c.practice.title} intro={c.practice.intro}><div className="grid gap-4 lg:grid-cols-2"><InfoCard title="DO" tone="accent"><ul className="list-disc space-y-2 pl-5">{c.practice.dos.map((item) => <li key={item}>{item}</li>)}</ul></InfoCard><InfoCard title="DON’T" tone="coral"><ul className="list-disc space-y-2 pl-5">{c.practice.donts.map((item) => <li key={item}>{item}</li>)}</ul></InfoCard></div><div className="mt-4 grid gap-3 md:grid-cols-3"><InfoCard title={locale === 'zh' ? '计划文档层级' : 'Planning hierarchy'}>{c.practice.docs}</InfoCard><InfoCard title={locale === 'zh' ? '健康 QA 环境' : 'Healthy QA environment'}>{c.practice.environment}</InfoCard><InfoCard title={locale === 'zh' ? '测试管理工具' : 'Test-management tools'}>{c.practice.tools}</InfoCard></div></ContentSection>
      <ContentSection id="project" index="07" title={c.project.title} intro={c.project.intro}><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{c.project.phases.map(([phase, title, items]) => <InfoCard key={phase} title={`${phase} · ${title}`} tone="accent"><ul className="list-disc space-y-2 pl-5">{items.map((item) => <li key={item}>{item}</li>)}</ul></InfoCard>)}</div></ContentSection>
      <ContentSection id="review" index="08" title={c.review.title} intro={c.review.intro}><div className="mb-4 grid gap-3 md:grid-cols-3">{c.review.memory.map(([title, body]) => <InfoCard key={title} title={title} tone="accent">{body}</InfoCard>)}</div><QuizAccordion items={c.review.quiz.map(([question, answer]) => ({ question, answer }))} /></ContentSection>
      <ContentSection id="sources" index="09" title={c.sourcesTitle} intro={c.sourcesIntro}><div className="grid gap-2 sm:grid-cols-2">{sources.map(([title, label, url]) => url ? <a key={title} href={url} target="_blank" rel="noreferrer" className="group rounded-xl border bg-card px-4 py-3 transition-colors hover:bg-[var(--week-accent-soft)]"><span className="flex items-center justify-between gap-3 text-sm font-bold">{title}<ExternalLink className="size-3.5 text-muted-foreground group-hover:text-foreground" /></span><span className="mt-1 block text-xs text-muted-foreground">{label}</span></a> : <div key={title} className="rounded-xl border bg-card px-4 py-3"><span className="text-sm font-bold">{title}</span><span className="mt-1 block text-xs text-muted-foreground">{label}</span></div>)}</div><Callout label={locale === 'zh' ? '材料边界' : 'Material boundary'}>{c.boundary}</Callout><figure className="mt-5 overflow-hidden rounded-2xl border bg-card"><img src={qualityVisual} alt="Mastering Software Quality: measurement and management" className="h-auto w-full" loading="lazy" /><figcaption className="px-4 py-3 text-xs text-muted-foreground">Quality Measurement and Management · Week 06 own-time</figcaption></figure></ContentSection>
    </WeekLayout>
  )
}
