import { ExternalLink } from 'lucide-react'
import { QuizAccordion } from '@/components/quiz-accordion'
import { Callout, ContentSection, InfoCard, LeadCard, ResponsiveTable, WeekLayout } from '@/components/week-layout'
import leadershipBlueprint from '@/assets/week03-leadership-blueprint.png'
import type { Locale } from '@/i18n'

const sourceItems = [
  ['Conflict in Teams - Causes, Prevention and Resolving', 'FIT5122 course PDF · 3 pages', null],
  ['Thomas-Kilmann Conflict Model', 'Management Weekly', 'https://managementweekly.org/thomas-kilmann-conflict-resolution-model/'],
  ['Human Logic and IT Conflict Modes', 'Course audio transcript · 06:14', null],
  ['The Top 7 Management Styles', 'Workzone', 'https://www.workzone.com/blog/management-styles/'],
  ['Everything Is About Time', 'Project Management Institute', 'https://www.pmi.org/learning/library/everything-time-monochronism-polychronism-orientation-6902'],
  ['Three Tips for Building High-Performing Teams', 'Cisco / Forbes', 'https://www.forbes.com/sites/jacobmorgan/2016/04/06/the-chief-people-officer-of-cisco-shares-her-top-three-tips-for-building-high-preforming-teams/'],
  ["The IT Leader's Blueprint", 'Course visual', null],
] as const

const copy = {
  zh: {
    title: 'Leadership & Conflict', subtitle: '建立信任，灵活处理分歧',
    summary: 'IT 团队像复杂系统：个人优势、共享价值和心理安全构成高绩效基础；冲突则需要被预防、诊断，并按情境选择合适的领导与处理模式。',
    tags: ['7 份 own-time 材料', 'TKI 五种模式', '7 种管理风格', '10 道自测'],
    toc: ['高绩效基础', '冲突生命周期', 'TKI 模型', '模式选择', '管理风格', '文化与时间', '团队 Playbook', '速记自测', '材料索引'],
    performance: {
      title: '高绩效先从团队环境开始', intro: '技术能力只是输入。团队是否敢于暴露问题、承担风险并拥有工作，决定这些能力能否组合成结果。',
      lead: 'Play to strengths + Share values + Have each other’s back.',
      leadNote: 'Cisco 的三项建议形成一条因果链：识别每个人的独特优势，让成员感到价值观被尊重，进而建立安全、信任和愿意共同承担风险的环境。',
      cards: [['Individual strengths', '了解每个人擅长什么、怎样工作最佳，并让任务匹配优势，而不是强迫所有人使用同一种方式。'], ['Shared values', '个人价值与组织使命能够连接时，成员更愿意提出不同意见并投入责任。'], ['Psychological safety', '队友会 back-stop 彼此；掉球被当作可恢复事件，而不是触发指责的 cascade failure。'], ['Autonomy & ownership', '过度指令会关闭创造性解决问题；自治让成员拥有工作，并推动专业成长与满意度。']],
      warning: 'Trust 不代表没有冲突。高信任团队仍会出现“系统 bug”，但能把问题视为共同调试，而不是寻找替罪羊。',
    },
    conflict: {
      title: '冲突生命周期：预防、解决、跟进', intro: '冲突不总是有害；尊重地处理任务分歧可以改善决策。问题是未澄清、被人格化或长期积累的 unhealthy conflict。',
      causes: [['Poor communication', '信息不清、倾听不足或不同解释造成误解。'], ['Different approaches', '文化、工作习惯、领导方式或技术方法被视为威胁，而非可组合的优势。'], ['Unclear roles / objectives', '角色、目标、优先级和责任边界不清，产生不同期待。'], ['People & change', '人格、工作伦理、职业价值、情绪触发点和抗拒变化产生摩擦。']],
      prevention: ['主动倾听：等待对方说完、提问澄清、总结并复述。', '留意双方 body language，建立良好 feedback loop。', '尊重并建设性延伸他人想法，允许 alternate solutions。', '提前约定沟通、文档、任务与决策标准，建立 Social Contract。', '确保每个人能发言；在问题升级前专业、面对面处理。', '定期检查 team dynamics，而不是等到事故才行动。'],
      resolution: ['寻找 root cause，依据 facts，把人和问题分开。', '理解对方立场，保持冷静、友好与专业。', '使用 I-statements 表达感受、利益和合作请求。', '需要时道歉并原谅，不保留 resentment。', '团队无法解决时，请 mediator 或 formal authority 协助。'],
      personal: ['承担自己在冲突中的责任。', '识别 emotional triggers，并有意识控制反应。', '清楚、assertively 表达问题、感受、利益与关切。', '不打断地听对方立场，开放且包容地生成方案。', '约定近期 follow-up，必要时寻求帮助并照顾自己。'],
    },
    tki: {
      title: 'Thomas-Kilmann：两条轴，五种模式', intro: 'Assertiveness 表示保护自己关切的程度；Cooperativeness 表示帮助对方满足关切的程度。模式没有道德高低，关键是情境匹配。',
      axes: [['Assertiveness', '我需要多大程度坚持自己的目标、风险判断与责任？'], ['Cooperativeness', '我需要多大程度帮助对方满足其关切并保护关系？']],
      modes: [['Competing', '高 assertiveness · 低 cooperation', '危机、不可妥协风险或必须快速决策。IT 情境：发现关键漏洞时强制 security freeze。'], ['Collaborating', '高 assertiveness · 高 cooperation', '双方关切都重要，需要真正 win-win 与 buy-in。IT 情境：整合两条技术 roadmap。'], ['Compromising', '两个维度均中等', '时间有限、权力相近、good enough 即可。IT 情境：在 deadline 前分配有限预算或资源。'], ['Avoiding', '低 assertiveness · 低 cooperation', '议题琐碎、情绪过热或需要先收集事实。IT 情境：暂停失控的 Friday retrospective，周一再谈。'], ['Accommodating', '低 assertiveness · 高 cooperation', '自己可能错误，或议题对对方更重要。IT 情境：放弃低价值命名偏好，换取关系与推进力。']],
      default: '多数人有一个舒适的 default mode。专业成长来自扩大 repertoire：能在不自然但更适合情境的模式中行动。',
    },
    selection: {
      title: '选择模式，也要看到过度使用的代价', intro: '先判断紧迫性、议题重要度、关系价值、权力结构、事实完整度和可用时间，再选模式。',
      headers: ['模式', '优先使用情境', '过度使用的风险'],
      rows: [['Competing', '危机、快速决定、重要但不受欢迎的行动、保护团队底线', '成员停止报告问题，形成 yes-people，信息枯竭'], ['Collaborating', '关切不可牺牲、需要认同、整合观点、修复深层关系', '无休止会议、琐事共识、decision paralysis'], ['Compromising', '目标中等重要、双方势均力敌、临时方案或时间压力', '双方都不满意，原则被 split-the-difference 稀释'], ['Avoiding', '议题琐碎、情绪太高、需要信息或介入成本更大', '问题发酵、决策停滞、成员觉得没有被听见'], ['Accommodating', '自己错误、议题对对方更重要、积累 goodwill、优先稳定', '自己的观点消失，被利用并积累安静的 resentment']],
      guide: [['Fast & vital', 'Competing'], ['Too important to trade', 'Collaborating'], ['Equal power + deadline', 'Compromising'], ['Trivial / emotions high', 'Avoiding'], ['Wrong / matters more to them', 'Accommodating']],
    },
    management: {
      title: '七种管理风格：没有万能领导方式', intro: '风格要与领导者能力、团队成熟度、组织文化和任务风险匹配。错误风格会降低动机、生产力与留任。',
      styles: [['Authoritarian', '清楚方向、集中控制和严格角色。适合危机、新手团队或必须快速统一行动；过度会变成 micromanagement 和决策瓶颈。'], ['Visionary', '说明 why 与整体方向，把 how 交给团队。适合变革或重新对齐成熟团队；缺少细节会让新手迷失。'], ['Transactional', '用奖金、激励等 extrinsic reward 换取明确结果。适合短期、不受欢迎的任务；长期使用损害内在动机与创新。'], ['Servant Leadership', '通过 coaching、mentoring 和支持发展成员。能建立信任与成长；耗时，且对不投入或不适配者效果有限。'], ['Pacesetting', '领导者示范高标准与速度。适合有能力、有动机的团队冲刺短期挑战；持续 stretch 会 burnout、分裂与失去士气。'], ['Democratic', '主动收集所有层级的意见，经理保留最终决定。提高被重视感、责任与创新；代价是时间和可能的伪参与感。'], ['Laissez-Faire', '提供目标与信息后，让自我驱动的专家决定 how。促进自治与创新；缺少自我管理或在关键项目上容易太晚发现风险。']],
      rule: '管理风格与 TKI 的共同原则：comfort zone 不是答案。读懂情境，清楚说明为何切换，并持续观察效果。',
    },
    time: {
      title: '文化与时间：同一个 deadline，不同心理模型', intro: 'Monochronic 与 Polychronic 是相对倾向，不是对国家或个人的诊断。项目经理要管理差异，而不是把一方定义为不专业。',
      headers: ['取向', '时间模型', '项目行为', '常见误读'],
      rows: [['Monochronic 单时', '线性、可度量、稀缺且可“花费”', '一次一事、计划、准时、期限优先、doing', '把弹性和关系活动看作浪费或不可靠'], ['Polychronic 多时', '多个事件并行，时间受关系与事件影响', '多任务、完成互动、关系优先、时间弹性、being', '把严格时间控制看作冷漠、僵化或破坏关系']],
      tension: 'Monochronic 成员可能把迟到解释为不尊重；Polychronic 成员可能把中断重要谈话去赶下一项解释为不尊重关系。双方使用同一个“尊重”概念，却指向不同对象。',
      communication: ['不要依据文化概括立即判断个人；先获取事实。', 'Receiver—not sender—defines communication；让对方复述收到的意思。', '敏感或困难信息优先面对面处理，再用邮件确认。', '明确任务、时间窗、优先级、变更通知、关系活动与责任人。', '避免 colloquialisms，持续发展 cultural sensitivity。'],
    },
    playbook: {
      title: '把领导与冲突能力写进团队系统', intro: '优秀团队不靠成员临场发挥；它把预防、决策、升级与学习方式变成可执行规则。',
      actions: [['Strength map', '记录每个人的优势、工作偏好和需要的支持，让任务匹配能力。'], ['Shared values', '把组织使命与成员重视的质量、用户、成长和协作原则连接起来。'], ['Social Contract', '提前约定沟通、文档、响应、会议、任务 ownership 与 disagreement。'], ['Active listening', '使用 Listen → Clarify → Summarize → Confirm，减少误读。'], ['Conflict triage', '先判断事实、情绪、风险和时间，再选择 TKI 模式。'], ['Separate people/problem', '聚焦行为、影响、根因和方案，不评价人格。'], ['Autonomy with guardrails', '给专家决定 how 的空间，同时设置可见性、检查点与风险升级。'], ['Follow-through', '记录决定、owner 与 deadline；约定 follow-up，回顾模式是否有效。']],
      final: 'IT leadership 不只是写出优雅系统，而是建立信任，并在 roadmap 冲突时协作、在情绪失控时暂停、在安全底线受威胁时敢于拉下 emergency brake。',
    },
    review: {
      title: '六组速记 + 十题自测', intro: '记住“基础—预防—诊断—选模式—跟进”，再用情境判断。点击题目展开答案。',
      memory: [['Cisco 3', 'Strengths · Shared values · Have each other’s back'], ['TKI axes', 'Assertiveness × Cooperativeness'], ['TKI 5', 'Compete · Collaborate · Compromise · Avoid · Accommodate'], ['Conflict', 'Facts · Separate person/problem · Listen · I-statement'], ['Time', 'Mono：schedule；Poly：relationship + flexibility'], ['Leadership', 'Style follows team, task, culture, risk—not ego']],
      quiz: [['冲突是否一定代表团队失败？', '不是。尊重地处理任务分歧可以改善决策；有害的是未澄清、人格化和长期积累的冲突。'], ['TKI 两条轴分别是什么？', 'Assertiveness：坚持自己关切；Cooperativeness：帮助对方满足关切。'], ['发现关键安全漏洞、必须立即停止发布，应选择什么模式？', 'Competing。此时不妥协是 stewardship，而非攻击；延迟成本远低于泄露风险。'], ['两条重要 roadmap 都不能牺牲，且需要共同认同，应选什么？', 'Collaborating。公开真实约束，寻找比任何单方方案更好的整合答案。'], ['Avoiding 何时是技能而不是逃避？', '情绪太高、事实不足、议题琐碎或此刻介入伤害更大，并且明确安排后续处理。'], ['Compromising 与 Collaborating 最关键区别是什么？', 'Compromising 通过各自让步得到中间方案；Collaborating 深挖关切，寻找同时满足双方的整合方案。'], ['为什么持续 Pacesetting 可能伤害团队？', '长期高压 stretch 会造成 burnout、分裂、失去动机，并让能力不足者被设定为失败。'], ['Laissez-Faire 在什么团队最可能有效？', '自我驱动、技能强、能管理时间和解决问题的专家团队，且有清楚目标与风险 guardrails。'], ['Monochronic 与 Polychronic 的冲突本质是什么？', '一方优先计划与期限，另一方优先关系与完成互动；双方对时间与尊重的定义不同。'], ['当冲突涉及自己时，第一步和最后一步是什么？', '先承担自己的责任并检查情绪触发；最后约定 follow-up、寻求所需帮助并照顾自己。']],
    },
    sourcesTitle: 'Own-time 材料索引', sourcesIntro: '本页覆盖目录中全部 7 份有效材料；公开文章链接原站，课程 PDF、音频转录和课程图不作为可下载原文件发布。', sourceBoundary: 'TKI 与管理风格是情境工具，不是人格标签；文化时间观是待验证的相对倾向，不应用来按国籍判断个人。',
  },
  en: {
    title: 'Leadership & Conflict', subtitle: 'Build trust and flex through disagreement',
    summary: 'An IT team behaves like a complex system: individual strengths, shared values, and psychological safety form the base; conflict must be prevented, diagnosed, and handled with the leadership mode the situation needs.',
    tags: ['7 own-time materials', '5 TKI modes', '7 management styles', '10 self-checks'], toc: ['High-performance foundations', 'Conflict lifecycle', 'TKI model', 'Mode selection', 'Management styles', 'Culture & time', 'Team playbook', 'Review', 'Sources'],
    performance: { title: 'High performance starts with the team environment', intro: 'Technical ability is only an input. Whether people can surface problems, take risks, and own the work determines whether those abilities combine into results.', lead: 'Play to strengths + Share values + Have each other’s back.', leadNote: 'Cisco’s three recommendations form a chain: recognise unique strengths, help people feel their values are respected, and build the safety and trust to take risks together.', cards: [['Individual strengths', 'Understand what makes each person distinctive and how they work best; align tasks instead of enforcing one method.'], ['Shared values', 'When personal values connect to mission, people are more willing to challenge, contribute, and own outcomes.'], ['Psychological safety', 'Teammates back-stop each other; a dropped ball becomes recoverable instead of starting a cascade of blame.'], ['Autonomy & ownership', 'Over-instruction suppresses creative problem-solving; autonomy creates ownership, growth, and satisfaction.']], warning: 'Trust does not mean no conflict. A high-trust team still has system bugs, but treats them as shared debugging rather than a hunt for blame.' },
    conflict: { title: 'Conflict lifecycle: prevent, resolve, follow through', intro: 'Conflict is not inherently harmful; respectful task disagreement can improve decisions. Unclear, personalised, and accumulating conflict becomes unhealthy.', causes: [['Poor communication', 'Unclear information, weak listening, and differing interpretations create misunderstanding.'], ['Different approaches', 'Culture, work habits, leadership, or technical methods are treated as threats rather than combinable strengths.'], ['Unclear roles / objectives', 'Ambiguous goals, priorities, responsibility, and boundaries create incompatible expectations.'], ['People & change', 'Personality, work ethic, professional values, triggers, and resistance to change create friction.']], prevention: ['Listen actively: wait, clarify, summarise, and repeat back.', 'Read body language and establish a healthy feedback loop.', 'Respect and build on ideas; remain open to alternatives.', 'Set communication, documentation, task, and decision standards in a Social Contract.', 'Give everyone a voice; address issues professionally and face-to-face before escalation.', 'Review team dynamics routinely, not only after an incident.'], resolution: ['Find root cause, use facts, and separate the person from the problem.', 'Understand the other view while staying calm, friendly, and professional.', 'Use I-statements to express feeling, interests, and a request to collaborate.', 'Apologise and forgive when needed rather than retain resentment.', 'Use a mediator or formal authority when the team cannot resolve it.'], personal: ['Own your part in the conflict.', 'Identify emotional triggers and consciously regulate the response.', 'State the problem, feeling, interests, and concerns assertively.', 'Listen without interruption and generate solutions openly.', 'Schedule a near-term follow-up, seek support, and look after yourself.'] },
    tki: { title: 'Thomas-Kilmann: two axes, five modes', intro: 'Assertiveness is the extent to which you protect your own concerns; Cooperativeness is how much you help the other person meet theirs. Modes are not moral ranks—the test is contextual fit.', axes: [['Assertiveness', 'How strongly must I protect my goal, risk judgement, and responsibility?'], ['Cooperativeness', 'How strongly must I help the other party meet their concern and protect the relationship?']], modes: [['Competing', 'High assertiveness · low cooperation', 'Crisis, non-negotiable risk, or a fast decision. IT example: enforce a security freeze on a critical vulnerability.'], ['Collaborating', 'High assertiveness · high cooperation', 'Both concerns matter and genuine win-win and buy-in are needed. IT example: integrate two technology roadmaps.'], ['Compromising', 'Moderate on both axes', 'Time is limited, power is equal, and good enough works. IT example: allocate scarce resources before a deadline.'], ['Avoiding', 'Low assertiveness · low cooperation', 'The issue is trivial, emotion is too high, or facts are missing. IT example: pause a destructive Friday retrospective and return Monday.'], ['Accommodating', 'Low assertiveness · high cooperation', 'You may be wrong or it matters more to them. IT example: concede a low-value naming preference to protect momentum.']], default: 'Most people have a comfortable default. Professional growth expands the repertoire so you can use an unfamiliar mode when the situation needs it.' },
    selection: { title: 'Choose the mode—and see the cost of overuse', intro: 'Assess urgency, importance, relationship value, power, available facts, and time before choosing.', headers: ['Mode', 'Reach for it when', 'Risk of overuse'], rows: [['Competing', 'Crisis, rapid call, vital unpopular action, protecting a boundary', 'People stop reporting problems; yes-people and information loss'], ['Collaborating', 'Concerns cannot be traded, buy-in and integrated learning needed', 'Endless meetings, trivial consensus, decision paralysis'], ['Compromising', 'Moderate stakes, equal power, temporary answer or time pressure', 'No one satisfied; principles disappear into split-the-difference'], ['Avoiding', 'Trivial issue, high emotion, missing information, intervention costs more', 'Problems fester, decisions stall, people feel unheard'], ['Accommodating', 'You are wrong, it matters more to them, goodwill or stability first', 'Your ideas disappear, exploitation and quiet resentment']], guide: [['Fast & vital', 'Competing'], ['Too important to trade', 'Collaborating'], ['Equal power + deadline', 'Compromising'], ['Trivial / emotions high', 'Avoiding'], ['Wrong / matters more to them', 'Accommodating']] },
    management: { title: 'Seven management styles: no universal way to lead', intro: 'Style must fit the leader’s capability, team maturity, organisational culture, and task risk. A mismatch harms motivation, productivity, and retention.', styles: [['Authoritarian', 'Clear direction, central control, strict roles. Useful in crisis or with inexperienced teams; overuse becomes micromanagement and a bottleneck.'], ['Visionary', 'Communicate why and direction, entrust the team with how. Useful for change and alignment; missing detail leaves inexperienced teams lost.'], ['Transactional', 'Use extrinsic rewards for defined outputs. Useful for short, unwanted tasks; long use harms intrinsic motivation and innovation.'], ['Servant Leadership', 'Coach, mentor, and support growth. Builds trust and capability; costs time and may not help someone disengaged or poorly fitted.'], ['Pacesetting', 'Model high standards and speed. Useful for a capable, motivated team and short challenge; sustained stretch creates burnout and division.'], ['Democratic', 'Seek input across levels while the manager retains the decision. Improves voice, ownership, and ideas; costs time and can feel performative.'], ['Laissez-Faire', 'Set direction and information, then let experts decide how. Supports autonomy and innovation; weak self-management or critical projects may hide risk too long.']], rule: 'Management style and TKI share one principle: the comfort zone is not the answer. Read the situation, explain the switch, and observe its effect.' },
    time: { title: 'Culture and time: one deadline, different mental models', intro: 'Monochronic and Polychronic are relative tendencies, not diagnoses of nations or individuals. Project leaders manage the difference rather than label one side unprofessional.', headers: ['Orientation', 'Time model', 'Project behaviour', 'Common misreading'], rows: [['Monochronic', 'Linear, measurable, scarce, spendable', 'One task, plans, punctuality, deadlines, doing', 'Flexibility and relationship work look wasteful or unreliable'], ['Polychronic', 'Several events; time follows relationships and events', 'Multitask, complete interaction, relationship priority, flexibility, being', 'Strict clock control looks cold, rigid, or destructive to relationships']], tension: 'A monochronic colleague may read lateness as disrespect; a polychronic colleague may read leaving an important conversation for the next task as disrespect. Both invoke respect, but protect a different object.', communication: ['Do not judge an individual from a cultural generalisation; collect facts.', 'The receiver—not the sender—defines communication; ask them to summarise what they heard.', 'Use face-to-face conversation for sensitive messages, then confirm in writing.', 'Make task, window, priority, change notice, relationship time, and ownership explicit.', 'Avoid colloquialisms and keep developing cultural sensitivity.'] },
    playbook: { title: 'Build leadership and conflict skill into the team system', intro: 'Strong teams do not rely on improvisation. They make prevention, decisions, escalation, and learning executable.', actions: [['Strength map', 'Record strengths, work preferences, and needed support; align work with capability.'], ['Shared values', 'Connect mission to members’ commitments to users, quality, growth, and collaboration.'], ['Social Contract', 'Agree communication, documentation, response, meetings, task ownership, and disagreement.'], ['Active listening', 'Use Listen → Clarify → Summarise → Confirm to reduce interpretation errors.'], ['Conflict triage', 'Assess facts, emotion, risk, and time before selecting a TKI mode.'], ['Separate people/problem', 'Focus on behaviour, impact, root cause, and solution—not personality.'], ['Autonomy with guardrails', 'Let experts decide how while maintaining visibility, checkpoints, and escalation.'], ['Follow-through', 'Record decision, owner, and deadline; follow up and review whether the mode worked.']], final: 'IT leadership is not only elegant systems. It is building trust, collaborating across roadmaps, pausing when emotion overwhelms facts, and pulling the emergency brake when security is at risk.' },
    review: { title: 'Six memory lines + ten self-checks', intro: 'Remember foundation → prevention → diagnosis → mode → follow-up, then judge the scenario. Select a question to reveal the answer.', memory: [['Cisco 3', 'Strengths · Shared values · Have each other’s back'], ['TKI axes', 'Assertiveness × Cooperativeness'], ['TKI 5', 'Compete · Collaborate · Compromise · Avoid · Accommodate'], ['Conflict', 'Facts · Separate person/problem · Listen · I-statement'], ['Time', 'Mono: schedule; Poly: relationship + flexibility'], ['Leadership', 'Style follows team, task, culture, risk—not ego']], quiz: [['Does conflict always mean team failure?', 'No. Respectful task disagreement can improve decisions; unclear, personalised, and accumulating conflict is harmful.'], ['What are the two TKI axes?', 'Assertiveness protects your concerns; Cooperativeness helps the other party meet theirs.'], ['A critical security vulnerability requires an immediate release stop. Which mode?', 'Competing. Refusing to compromise is stewardship here; delay costs far less than a breach.'], ['Two important roadmaps cannot be sacrificed and need real buy-in. Which mode?', 'Collaborating. Expose real constraints and find an integrated answer better than either original position.'], ['When is Avoiding a skill rather than escape?', 'When emotion is too high, facts are missing, the issue is trivial, or immediate engagement causes more harm—and a return is scheduled.'], ['What distinguishes Compromising from Collaborating?', 'Compromising trades concessions for a middle answer; Collaborating investigates concerns and creates an integrated solution.'], ['Why can sustained Pacesetting harm a team?', 'Continuous stretch creates burnout, division, and lost motivation while setting less-ready members up to fail.'], ['Where is Laissez-Faire most likely to work?', 'With self-motivated experts who manage time and solve problems, under clear goals and risk guardrails.'], ['What drives Monochronic / Polychronic conflict?', 'One prioritises plan and deadline; the other relationship and completed interaction. They define time and respect differently.'], ['When conflict involves you, what are the first and last steps?', 'First own your contribution and regulate triggers; finally schedule follow-up, seek support, and care for yourself.']] },
    sourcesTitle: 'Own-time material index', sourcesIntro: 'This page covers all seven valid materials in the folder. Public articles link to originals; the course PDF, audio transcript, and visual are not published as downloadable source files.', sourceBoundary: 'TKI and management styles are situational tools, not personality labels. Cultural time orientations are hypotheses to verify, not a basis for judging individuals by nationality.',
  },
} as const

export default function Week03({ locale }: { locale: Locale }) {
  const c = copy[locale]
  const ids = ['performance', 'conflict', 'tki', 'selection', 'management', 'time', 'playbook', 'review', 'sources']
  const toc = ids.map((id, index) => ({ id, label: c.toc[index] }))
  return (
    <WeekLayout weekId="03" locale={locale} eyebrow="Week 03 · IT leadership" title={c.title} subtitle={c.subtitle} summary={c.summary} updated="04 Sep 2026" tags={[...c.tags]} toc={toc}>
      <ContentSection id="performance" index="01" title={c.performance.title} intro={c.performance.intro}><LeadCard label="Cisco · High-performance foundations" note={c.performance.leadNote}>{c.performance.lead}</LeadCard><div className="mt-4 grid gap-3 md:grid-cols-2">{c.performance.cards.map(([title, body], index) => <InfoCard key={title} title={title} tone={index % 2 ? 'accent' : 'blue'}>{body}</InfoCard>)}</div><Callout label={locale === 'zh' ? '关键边界' : 'Key boundary'}>{c.performance.warning}</Callout><figure className="mt-5 overflow-hidden rounded-2xl border bg-card"><img src={leadershipBlueprint} alt="IT leadership and conflict mastery blueprint" className="h-auto w-full" loading="lazy" /><figcaption className="px-4 py-3 text-xs text-muted-foreground">The IT Leader's Blueprint · Week 03 own-time visual</figcaption></figure></ContentSection>
      <ContentSection id="conflict" index="02" title={c.conflict.title} intro={c.conflict.intro}><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{c.conflict.causes.map(([title, body]) => <InfoCard key={title} title={title} tone="coral">{body}</InfoCard>)}</div><div className="mt-4 grid gap-4 lg:grid-cols-3"><InfoCard title={locale === 'zh' ? '预防行为' : 'Prevent'} tone="accent"><ul className="list-disc space-y-2 pl-5">{c.conflict.prevention.map((item) => <li key={item}>{item}</li>)}</ul></InfoCard><InfoCard title={locale === 'zh' ? '解决行为' : 'Resolve'}><ul className="list-disc space-y-2 pl-5">{c.conflict.resolution.map((item) => <li key={item}>{item}</li>)}</ul></InfoCard><InfoCard title={locale === 'zh' ? '当冲突涉及自己' : 'When you are involved'} tone="warm"><ul className="list-disc space-y-2 pl-5">{c.conflict.personal.map((item) => <li key={item}>{item}</li>)}</ul></InfoCard></div></ContentSection>
      <ContentSection id="tki" index="03" title={c.tki.title} intro={c.tki.intro}><div className="grid gap-4 md:grid-cols-2">{c.tki.axes.map(([title, body]) => <InfoCard key={title} title={title} tone="blue">{body}</InfoCard>)}</div><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-5">{c.tki.modes.map(([title, axes, body], index) => <InfoCard key={title} title={title} tone={index === 0 ? 'coral' : index === 1 ? 'accent' : index === 2 ? 'warm' : 'blue'}><p className="mb-2 text-xs font-black uppercase tracking-wider text-foreground">{axes}</p>{body}</InfoCard>)}</div><Callout label={locale === 'zh' ? '核心能力' : 'Core capability'}>{c.tki.default}</Callout></ContentSection>
      <ContentSection id="selection" index="04" title={c.selection.title} intro={c.selection.intro}><ResponsiveTable headers={[...c.selection.headers]} rows={c.selection.rows.map((row) => [...row])} /><h3 className="mb-4 mt-8 text-2xl font-black">{locale === 'zh' ? '快速决策线' : 'Quick decision line'}</h3><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{c.selection.guide.map(([trigger, mode]) => <InfoCard key={trigger} title={mode} tone="accent">{trigger}</InfoCard>)}</div></ContentSection>
      <ContentSection id="management" index="05" title={c.management.title} intro={c.management.intro}><div className="grid gap-3 md:grid-cols-2 lg:grid-cols-3">{c.management.styles.map(([title, body], index) => <InfoCard key={title} title={`${String(index + 1).padStart(2, '0')} · ${title}`} tone={index === 0 ? 'coral' : index === 4 ? 'warm' : index === 6 ? 'blue' : 'plain'}>{body}</InfoCard>)}</div><Callout label={locale === 'zh' ? '共同原则' : 'Shared principle'}>{c.management.rule}</Callout></ContentSection>
      <ContentSection id="time" index="06" title={c.time.title} intro={c.time.intro}><ResponsiveTable headers={[...c.time.headers]} rows={c.time.rows.map((row) => [...row])} /><Callout label={locale === 'zh' ? '冲突机制' : 'Conflict mechanism'}>{c.time.tension}</Callout><InfoCard title={locale === 'zh' ? '跨时间观协作' : 'Working across time orientations'} tone="accent" className="mt-4"><ul className="list-disc space-y-2 pl-5">{c.time.communication.map((item) => <li key={item}>{item}</li>)}</ul></InfoCard></ContentSection>
      <ContentSection id="playbook" index="07" title={c.playbook.title} intro={c.playbook.intro}><div className="grid gap-3 md:grid-cols-2">{c.playbook.actions.map(([title, body], index) => <InfoCard key={title} title={`${String(index + 1).padStart(2, '0')} · ${title}`} tone={index % 2 ? 'plain' : 'accent'}>{body}</InfoCard>)}</div><div className="mt-4"><LeadCard label={locale === 'zh' ? 'IT 领导力' : 'IT leadership'}>{c.playbook.final}</LeadCard></div></ContentSection>
      <ContentSection id="review" index="08" title={c.review.title} intro={c.review.intro}><div className="mb-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{c.review.memory.map(([title, body]) => <InfoCard key={title} title={title} tone="coral">{body}</InfoCard>)}</div><QuizAccordion items={c.review.quiz.map(([question, answer]) => ({ question, answer }))} /></ContentSection>
      <ContentSection id="sources" index="09" title={c.sourcesTitle} intro={c.sourcesIntro}><div className="grid gap-2 sm:grid-cols-2">{sourceItems.map(([title, label, url]) => url ? <a key={title} href={url} target="_blank" rel="noreferrer" className="group rounded-xl border bg-card px-4 py-3 transition-colors hover:bg-[var(--week-accent-soft)]"><span className="flex items-center justify-between gap-3 text-sm font-bold">{title}<ExternalLink className="size-3.5 text-muted-foreground group-hover:text-foreground" /></span><span className="mt-1 block text-xs text-muted-foreground">{label}</span></a> : <div key={title} className="rounded-xl border bg-card px-4 py-3"><span className="text-sm font-bold">{title}</span><span className="mt-1 block text-xs text-muted-foreground">{label}</span></div>)}</div><Callout label={locale === 'zh' ? '使用边界' : 'Use boundary'}>{c.sourceBoundary}</Callout></ContentSection>
    </WeekLayout>
  )
}
