import { ExternalLink } from 'lucide-react'
import { QuizAccordion } from '@/components/quiz-accordion'
import { Callout, ContentSection, InfoCard, LeadCard, ResponsiveTable, WeekLayout } from '@/components/week-layout'
import type { Locale } from '@/i18n'

const sourceItems = [
  ['FIT5122 - Basics for Effective Meetings', 'Course PDF · 8 pages', null],
  ['FIT5122 - Minutes: General Hints', 'Course PDF · 1 page', null],
  ['FIT5122 Notes on Presentations', 'Course PDF · 7 pages', null],
  ['Using Gen-AI Responsibly', 'Course video transcript · 10:11', null],
  ['Avoid Ad Hoc Meeting Tips', 'Runn', 'https://www.runn.io/blog/ad-hoc-meeting'],
  ['How to Effectively Chair or Facilitate a Meeting', 'Resource Centre', 'https://www.resourcecentre.org.uk/information/chairing-a-meeting/'],
  ['How to Design an Agenda for an Effective Meeting', 'Harvard Business Review', 'https://hbr.org/2015/03/how-to-design-an-agenda-for-an-effective-meeting'],
  ['Professional Risks of Using LLMs', 'New York Times · Avianca case', 'https://www.nytimes.com/2023/05/27/nyregion/avianca-airline-lawsuit-chatgpt.html'],
  ['Writing an Agenda that Enables an Effective Meeting', 'wikiHow', 'https://www.wikihow.com/Write-an-Agenda-for-a-Meeting'],
  ["14 Dos and Don'ts for an Effective Presentation", 'Renderforest', 'https://www.renderforest.com/blog/tricks-for-an-effective-presentation'],
  ['How to Run Effective Meetings: Five Principles', 'Slack', 'https://slack.com/intl/en-au/blog/productivity/run-effective-meetings'],
  ['How to Run a Great Virtual Meeting', 'Harvard Business Review', 'https://hbr.org/2015/03/how-to-run-a-great-virtual-meeting'],
  ['How to Structure Your Messages Quickly', 'Entrepreneur', 'https://www.entrepreneur.com/growing-a-business/3-ways-effective-communicators-structure-unforgettable/294398'],
  ['Strategies for Delivering Impromptu Presentations', 'LinkedIn', 'https://www.linkedin.com/pulse/how-give-impromptu-speeches-without-fear-philipp-humm-dtkte/'],
] as const

const copy = {
  zh: {
    title: 'Meetings, Messages & AI', subtitle: '设计协作，也为自己的判断负责',
    summary: '专业沟通不是“多说一点”：选择正确渠道、设计有结果的会议、让信息易于理解，并对使用 Gen-AI 后提交的每项主张承担证据与伦理责任。',
    tags: ['14 份 own-time 材料', '会议全生命周期', '4 个表达框架', '12 道自测'],
    toc: ['沟通决策', '会议设计', '主持与参与', '纪要与跟进', '虚拟与 Ad Hoc', '有效演示', '快速表达', 'Gen-AI 责任', '速记自测', '材料索引'],
    map: {
      title: '先选择正确的沟通形式', intro: '会议、演示、消息和 AI 工具都只是手段。先定义需要发生的结果，再选择成本最低、最能支持理解与责任的方式。',
      lead: 'Choose → Design → Facilitate → Record → Present → Verify.',
      cards: [['Choose · 是否要开会', '只有需要共同判断、协作、共识或即时解决问题时才同步开会；单向更新优先异步。'], ['Design · 为结果设计', '明确目标、参与者、议程、时间、角色、决策方式和 pre-work。'], ['Facilitate · 让所有人参与', '主席管理流程而非垄断观点，平衡业务推进、发言公平与清楚决定。'], ['Record · 留下可执行记忆', '纪要记录结论、关键理由、行动、owner 和 deadline，而不是逐字转录。'], ['Present · 围绕听众表达', '把结构、故事、声音、视觉和 body language 都服务于一条 key message。'], ['Verify · 对主张负责', 'Gen-AI 可辅助生成，但人必须独立核验并能回答“为什么相信这项结论”。']],
      rule: '高质量沟通的共同指标：接收者理解了什么、决定了什么、下一步由谁在何时完成，而不是发送者说了多少。',
    },
    design: {
      title: '设计会议：从“为什么”到行动条件', intro: '好的会议在邀请发出前已经开始。没有明确目的、需要共同参与的问题和预期产出，就不应占用同步时间。',
      filters: [['Purpose', '信息收集/分享、决策、问题解决、计划、共识、关系或必要的象征性活动。'], ['Participants', '只邀请需要提供信息、建议、专业知识或授权行动的人；旁听更新者可读摘要。'], ['Format', '根据风险与互动需要选择正式/非正式、同步/异步、线下/虚拟。'], ['Time & place', '考虑时区、精力、可访问性、sight lines、acoustics、权力象征和明确结束时间。']],
      agendaHeaders: ['Agenda 字段', '必须回答的问题', '用途'], agendaRows: [['Objective / outcome', '会议结束时需要决定、产生或确认什么？', '让参与者按同一成功标准准备'], ['Question / topic', '需要共同回答的具体问题是什么？', '比宽泛主题更能推动讨论完成'], ['Priority & time', '哪项最重要？每项真实需要多久？', '先做关键项并控制结束时间'], ['Owner / role', '谁介绍、主持、记录、计时或批准？', '提前准备并避免责任空白'], ['Process', '信息分享、brainstorm、voting、consensus 还是 leader decision？', '让讨论方式匹配产出'], ['Pre-work', '会前需要阅读、研究或征求谁的意见？', '把报告移出会议，把时间留给判断']],
      preparation: ['征求成员议题建议，但只保留需要多人参与且与目标相关的项目。', '按重要度排序；给每项估时并说明负责人。', '附日期、地点/链接、参与者、资料和明确的开始/结束时间。', '提前分发并校对；允许成员准备问题、立场与证据。'],
      power: '结构不等于公平。正式程序可以让所有人参与，也可能强化主席或少数人的 power concentration；座位、发言顺序和决策规则都会改变谁能影响结果。',
    },
    chair: {
      title: '主持不是发表最多意见', intro: 'Chair / facilitator 的任务是帮助团队按时讨论完业务、让观点被听见、形成清楚决定；主席无法替代参与者的准备和合作。',
      before: ['与秘书和成员共同明确目标、资料、议题与需要的 speaker。', '确定并解释会议规则：不打断、聚焦议题、尊重异议、简洁发言、准时开始结束。', '欢迎新成员，确保所有人有 agenda、背景和参与所需信息。'],
      four: [['Get through business', '介绍每项议题、说明为何讨论、看时间、acknowledge 但 park 离题内容，并解释何时结束讨论。'], ['Involve everyone', '限制过度发言者，优先邀请未发言者，保护 minority view，不能把 silence 当作 agreement。'], ['Reach decisions', '重述问题和所需决定，总结各立场，提出前进路径，移动议题前确认同一结论与 owner。'], ['Handle difficulty', '一致执行规则；把个人争执重述为问题；让持续批评者提出方案；必要时让团队决定是否继续。']],
      member: '成员也有责任：阅读 agenda 和前次 minutes、准时、专注、不打断、允许主席主持、愿意协商和修改立场，并在决定后执行。',
    },
    minutes: {
      title: 'Minutes：把讨论变成组织记忆', intro: '议程和纪要共同构成项目的 corporate / legal memory。纪要必须让缺席者知道发生了什么、为什么，以及接下来做什么。',
      items: [['Basics', '会议名称、日期、时间、地点/链接、主席、完整姓名的 attendees 与 apologies。'], ['Decision & context', '记录决定、关键理由及对缺席者有意义的重要 insight。'], ['Action', '写清任务、responsible person、due date 和需要的支持。'], ['Structure', '沿用 agenda 标题与稳定模板，用 bullet、bold 等突出 action / who / when。'], ['Brevity', '不是 word-for-word；保留三周后仍重要的结果与关键路径。'], ['Confirmation', '尽快完成并确认纪要，分享给相关人，跟踪 action 并在下次会前 follow up。']],
      recording: '录音前必须取得 permission。录音能保留细节，却也可能让成员戒备、降低真实表达并增加会议正式感；听不懂时仍应当场澄清。',
      metrics: [['Attendance & participation', '是否常缺席？是否总是同一批人发言？'], ['Duration', '是否经常超时或明显过短？'], ['Action completion', '任务是否按时完成，还是责任和期限不清？'], ['Feedback loop', '通过讨论、1:1、匿名调查或 poll 定期调整会议。']],
    },
    formats: {
      title: 'Virtual 与 Ad Hoc：同步时间必须值得', intro: '虚拟不是实体会议的劣化版本；Ad Hoc 也不是天然错误。关键是风险、紧迫性、准备需求和对 deep work 的成本。',
      decisionHeaders: ['情境', '首选形式', '理由'], decisionRows: [['需要紧急解决运营或客户危机', '短 Ad Hoc 同步会议', '快速交换观点、形成行动，等待可能扩大损失'], ['非紧急问题、请求、状态更新', 'Email / chat / async recording', '让接收者按优先级处理并保留文档'], ['复杂协作、共识或敏感议题', '计划好的同步会议', '需要双向互动、关系和即时澄清'], ['只需两人解决或单向播报', '直接沟通或 pre-read', '避免让无关成员承担 context-switching']],
      adHoc: ['写一句 purpose / mini-agenda，说明为何需要对方。', '设置短 timebox，只邀请直接受影响或能立即贡献的人。', '结束前确认 priority、deliverable、owner 和 timing。', '考虑成员当前 deadline 与 resourcing，不把自己的紧急感自动变成全队紧急。'],
      virtualBefore: ['尽量使用 video 读取情绪与非语言反应，但照顾合理的可访问性和个人情境。', '移除 report-outs：会前发 half-page update，会议只讨论问题与评论。', '完成 pre-read，并提前收集自己所代表团队的观点。'],
      virtualDuring: ['用 personal-professional check-in 建立 connection 与 candor。', '用 collaborative problem-solving 替代轮流报告。', '给每人 agenda time；依次提问或 pass，再用 “I might suggest” 提建议。', '避免 mute 后离场与 multitasking；指定 Yoda 维护坦诚、参与和尊重。', '结束前正式安排 5-10 分钟 water-cooler reflection，公开处理真实感受。'],
    },
    presentation: {
      title: '有效演示：听众、信息、结构与交付', intro: '“好演示”的标准不是 slide 漂亮，而是目标听众理解并记住 intended message。Presentation 不是把书面报告读出来。',
      principles: [['Audience & purpose', '先问 who is talking what to whom；根据听众知识、角色、文化、需求和预期行动调整内容。'], ['Key message', '用一句话定义 takeaway；开头突出、过程中持续连接、结尾再次明确。'], ['Logical structure', '提供足够但不过量的背景；用清楚标题和引导，让听众知道现在在哪里、将去哪里。'], ['Story & conversation', '用相关故事、例子和问题建立兴趣；以对人说话的自然语气，而非朗读稿件。'], ['Voice & body', '声音可听、清楚、有变化且速度适中；眼神、开放手势、移动和 pause 与信息一致。'], ['Visuals', '少字、可读、对比清楚；图片服务观点。演示离开 slides 仍应成立，避免 fancy distraction。']],
      rehearsal: ['完整写出并理清信息，但用 notes 提示而非朗读。', '穿正式服装、在真实地点、使用真实 AV 设备排练。', '录像回看或对 mock audience 演示，检查时间、声音、姿态和理解。', '提前到场测试 microphone、投影、网络和 backup slides。'],
      timing: '时间缩短时应删掉非必要内容、保护 key points 与 takeaway，不能靠加速语速塞完原计划。',
      group: 'Group presentation 要明确谁讲什么、分配 slides 而非模糊主题；开场介绍成员与分工，speaker 之间做好 handoff。',
    },
    structures: {
      title: '快速表达：四个可复用结构', intro: '结构帮助说话者组织和记忆，也帮助听众保持注意并准确回忆。根据沟通目的选择，而不是机械套模板。',
      headers: ['框架', '结构', '最适合'], rows: [['3-I', 'Issue → Illustration → Invitation', '对话、建议、rapport；用故事说明，再邀请回应'], ['3-W', 'What? → So what? → Now what?', '教学、说服、debate；定义问题、说明意义、给出下一步'], ['PSB', 'Problem → Solution → Benefit', '正式提案、demo、business/academic pitch；重点证明方案可行'], ['PREP', 'Point → Reason → Example → Point', '即兴回答与短演说；30 秒组织后清楚开合']],
      prep: '需要更长即兴表达时，可扩展为 P-R-E-R-E-P。练习陌生主题、录影回看，并检查 body language、pause 和 tone。',
      narrative: '通用演示骨架：Tell them what you are going to tell them → Tell them → Tell them what you told them。',
    },
    ai: {
      title: 'Gen-AI：输出可用，但责任不能外包', intro: 'LLM 的目标是生成语言上 plausible 的下一段文字，不是判断主张是否为真。流畅、自信和带引用的形式都不能替代证据。',
      concepts: [['Truth-indifference', '模型可能生成真或假的内容，但生成机制本身不以 veracity 为中心；这不是有意欺骗。'], ['Epistemic insouciance', '对信念是否有现实基础、是否得到最佳证据支持缺乏关心；对人而言，这是拒绝查证的风险态度。'], ['Minimal epistemic responsibility', '当你声称相信命题 p，至少应能回答：What reasons do you have for believing p?'], ['Professional accountability', '把 AI 内容放进团队报告，就是团队在为主张背书；生成者不能承担你的伦理或职业责任。']],
      caseTitle: 'Mata v. Avianca：让模型“自证”为什么失败',
      caseSteps: [['1 · Generate', '律师使用 ChatGPT 做法律研究，文件引用了多个不存在的判例与引文。'], ['2 · Reassure', '他又问同一个模型这些案例是否真实，模型以自信语气确认。'], ['3 · Submit', '虚构名称、docket、法官、日期和内部引用进入正式 court filing。'], ['4 · Detect', '对方律师与法官无法在 court dockets 或法律数据库找到案例，法院讨论潜在 sanctions。']],
      lesson: 'Self-verification is not independent verification。模型可以重复并强化自己的虚构；专业人员必须回到权威数据库、原始文件和可追踪证据。',
      checklist: ['独立核实名字、日期、统计、引用、法规、case 和 recommendation。', '打开原始来源并确认它真实存在、内容支持当前主张。', '记录 AI 在哪一步被使用、哪些内容由人修改和批准。', '检查 dataset、prompt、遗漏与 bias 可能如何塑造输出。', '当证据不足时明确不确定性，不把 plausibility 写成 fact。', '依据证据权重形成信念，并能向客户、团队或公众说明理由。'],
    },
    review: {
      title: '六组速记 + 十二题自测', intro: '先记成功条件，再用情境选择沟通形式。点击问题展开答案。',
      memory: [['Meeting filter', 'Need interaction / decision? If no → async'], ['Agenda', 'Objective · Question · Time · Owner · Process · Pre-work'], ['Chair', 'Business · Inclusion · Decision · Difficulty'], ['Minutes', 'Outcome · Reason · Action · Owner · Due'], ['Speaking', '3-I · 3-W · PSB · PREP'], ['AI', 'Plausible ≠ true · Verify independently · Human accountable']],
      quiz: [['什么时候不应召开会议？', '当内容只是单向更新、无需即时行动或能由两人解决时，优先 email、chat、共享文档或直接沟通。'], ['有效 agenda 必须使参与者知道什么？', '会议目标、要回答的问题、优先级和时间、议题 owner、讨论/决策过程、pre-work 与预期结果。'], ['主席的角色为什么不是“发表最多意见”？', '主席管理整体流程、时间、参与和决定；利用职位压制其他观点会破坏会议目的。'], ['为什么 silence 不能当作 agreement？', '成员可能紧张、被打断、处于少数或不清楚流程；主席必须主动确认并邀请未发言者。'], ['纪要最关键的 action 信息是什么？', 'What、responsible person、due date，以及理解任务所需的决定与关键理由。'], ['录音会议前需要什么，录音有哪些风险？', '先取得 permission；录音可能让人戒备、降低真实表达并使会议更正式。'], ['虚拟会议为什么应移除 report-outs？', '会前书面更新即可；同步时间应留给提问、协作解决问题和形成判断。'], ['Ad Hoc 会议什么时候合理？', '需要紧急解决运营或关系危机，等待会扩大损失；仍应有 purpose、timebox、小范围参与和明确行动。'], ['演示时间突然缩短时应如何处理？', '删掉非必要内容，保护 key message、关键点和 takeaway；不要靠加快语速覆盖全部原稿。'], ['PREP 的四步是什么？', 'Point → Reason → Example → Point reiterated。'], ['为什么让同一个 LLM 核验自己的引用不够？', '它可能重复并强化同一虚构；核验必须使用独立、权威、可追踪的来源。'], ['Minimal epistemic responsibility 要求什么？', '对自己声称相信的内容至少能够说明理由和相关证据，不能只回答“AI 这样说”。']],
    },
    sourcesTitle: 'Own-time 材料索引', sourcesIntro: '本页覆盖目录中的全部 14 份材料；公开文章链接原站，课程 PDF 与 Panopto transcript 不作为可下载原文件发布。', sourceBoundary: '会议与演示建议应按目的、听众和风险调整；统计数字用于理解材料中的问题规模，不应脱离来源和年份泛化。',
  },
  en: {
    title: 'Meetings, Messages & AI', subtitle: 'Design collaboration and own your judgement',
    summary: 'Professional communication is not “say more.” Choose the right channel, design meetings that produce outcomes, make information easy to follow, and remain evidentially and ethically responsible for every claim submitted after using Gen-AI.',
    tags: ['14 own-time materials', 'Meeting lifecycle', '4 speaking frameworks', '12 self-checks'], toc: ['Communication choice', 'Meeting design', 'Chairing & participation', 'Minutes & follow-up', 'Virtual & Ad Hoc', 'Effective presentations', 'Rapid speaking', 'Gen-AI responsibility', 'Review', 'Sources'],
    map: { title: 'Choose the communication form first', intro: 'Meetings, presentations, messages, and AI are means. Define the outcome, then choose the lowest-cost form that supports understanding and accountability.', lead: 'Choose → Design → Facilitate → Record → Present → Verify.', cards: [['Choose · Should this be a meeting?', 'Meet synchronously for shared judgement, collaboration, consensus, or urgent resolution; send one-way updates asynchronously.'], ['Design · Build for the outcome', 'Define objective, participants, agenda, time, roles, decision method, and pre-work.'], ['Facilitate · Include the room', 'The chair manages process rather than dominating views, balancing progress, fair participation, and clear decisions.'], ['Record · Create executable memory', 'Minutes capture outcomes, critical rationale, action, owner, and deadline—not a transcript.'], ['Present · Design for the audience', 'Structure, story, voice, visuals, and body language all serve one key message.'], ['Verify · Own the claim', 'Gen-AI can generate, but people independently verify and answer why they believe the conclusion.']], rule: 'The common measure of communication quality is what the receiver understood, what was decided, and who will do what by when—not how much the sender said.' },
    design: { title: 'Design the meeting: from why to action conditions', intro: 'A good meeting starts before the invitation. Without a clear purpose, a genuinely shared issue, and an expected output, synchronous time should not be used.', filters: [['Purpose', 'Gather/share information, decide, solve, plan, build consensus or relationships, or perform a necessary symbolic activity.'], ['Participants', 'Invite people who provide information, advice, expertise, or authority; information-only attendees can read the summary.'], ['Format', 'Choose formal/informal, synchronous/asynchronous, and physical/virtual based on risk and interaction.'], ['Time & place', 'Consider time zone, energy, accessibility, sight lines, acoustics, power signals, and a declared end.']], agendaHeaders: ['Agenda field', 'Question it must answer', 'Purpose'], agendaRows: [['Objective / outcome', 'What must be decided, produced, or confirmed?', 'A shared success condition for preparation'], ['Question / topic', 'What specific question requires the group?', 'Questions complete discussion better than broad topics'], ['Priority & time', 'What matters most and how long realistically?', 'Protect critical items and the end time'], ['Owner / role', 'Who introduces, chairs, records, times, or approves?', 'Preparation and no responsibility gap'], ['Process', 'Share, brainstorm, vote, seek consensus, or leader decision?', 'Match discussion method to output'], ['Pre-work', 'What must be read, researched, or consulted?', 'Move reports out; keep meeting time for judgement']], preparation: ['Ask for agenda input but keep only items requiring the group and serving the objective.', 'Prioritise, timebox, and name the owner of each item.', 'Include date, location/link, participants, materials, start, and end.', 'Proofread and distribute early enough for questions, positions, and evidence.'], power: 'Structure is not the same as fairness. Formal process can enable participation or concentrate power; seating, speaking order, and decision rules shape who influences the result.' },
    chair: { title: 'Chairing is not having the most to say', intro: 'A chair helps the group complete business on time, hear views, and reach clear decisions; they cannot replace participant preparation and cooperation.', before: ['Work with the secretary and members to define outcome, evidence, topics, and speakers.', 'Agree rules: no interruption, stay on item, respect dissent, be concise, start and finish on time.', 'Welcome newcomers and ensure everyone has the agenda, context, and material.'], four: [['Get through business', 'Introduce why each item matters, watch time, acknowledge and park tangents, explain when discussion will close.'], ['Involve everyone', 'Limit dominant speakers, invite quiet members, protect minority views, and never treat silence as agreement.'], ['Reach decisions', 'Restate the issue and decision, summarise positions, propose a path, then confirm agreement and owner.'], ['Handle difficulty', 'Apply rules consistently, reframe personal disputes as issues, ask critics for solutions, and let the group decide when to move on.']], member: 'Members also prepare: read agenda and prior minutes, arrive on time, focus, do not interrupt, allow the chair to facilitate, negotiate when needed, and implement decisions.' },
    minutes: { title: 'Minutes: turn discussion into organisational memory', intro: 'Agenda and minutes form the project’s corporate or legal memory. An absent reader must understand what happened, why, and what comes next.', items: [['Basics', 'Meeting, date, time, place/link, chair, full attendee names, and apologies.'], ['Decision & context', 'The decision, critical rationale, and insight an absent member needs.'], ['Action', 'Task, responsible person, due date, and needed support.'], ['Structure', 'Follow agenda headings and a stable template; visually emphasise action / who / when.'], ['Brevity', 'Not word-for-word; retain outcomes and critical paths that matter in three weeks.'], ['Confirmation', 'Complete and confirm promptly, share, track action, and follow up before the next meeting.']], recording: 'Get permission before recording. Recordings preserve detail but can make members guarded, reduce candour, and increase formality; clarify confusion during the meeting.', metrics: [['Attendance & participation', 'Do people miss it? Do only the same voices speak?'], ['Duration', 'Does it regularly overrun or finish suspiciously early?'], ['Action completion', 'Are actions timely, or are owner and deadline unclear?'], ['Feedback loop', 'Adjust through discussion, 1:1s, anonymous surveys, or polls.']] },
    formats: { title: 'Virtual and Ad Hoc: synchronous time must earn its cost', intro: 'Virtual is not a degraded physical meeting; Ad Hoc is not automatically wrong. Judge urgency, risk, preparation, and the cost to deep work.', decisionHeaders: ['Situation', 'Preferred form', 'Reason'], decisionRows: [['Urgent operational or client crisis', 'Short Ad Hoc synchronous meeting', 'Rapid exchange and action; waiting expands loss'], ['Non-urgent request, question, status', 'Email / chat / async recording', 'Recipient responds by priority and documentation remains'], ['Complex collaboration, consensus, sensitive issue', 'Planned synchronous meeting', 'Two-way interaction, relationship, immediate clarification'], ['Only two people or one-way report', 'Direct contact or pre-read', 'Avoid context-switching costs for others']], adHoc: ['Write a one-line purpose / mini-agenda and why attendance is needed.', 'Use a short timebox and only directly affected or immediately useful people.', 'Confirm priority, deliverable, owner, and timing before closing.', 'Consider current deadlines and resourcing; your urgency is not automatically everyone’s urgency.'], virtualBefore: ['Use video when practical to read reactions while respecting accessibility and personal context.', 'Remove report-outs: send a half-page update and discuss only questions and comments.', 'Complete pre-reads and collect the view of people you represent.'], virtualDuring: ['Use a personal-professional check-in to build connection and candour.', 'Replace report-outs with collaborative problem-solving.', 'Give each person agenda time; ask/pass, then advise in an “I might suggest” form.', 'Avoid leaving on mute and multitasking; appoint a Yoda to support candour, focus, and respect.', 'Reserve 5–10 minutes for a transparent water-cooler reflection before closing.'] },
    presentation: { title: 'Effective presentation: audience, message, structure, delivery', intro: 'A presentation is good when the intended audience understands and remembers the intended message—not when the slides look impressive. Do not read a written report aloud.', principles: [['Audience & purpose', 'Ask who is saying what to whom; adapt to knowledge, role, culture, need, and intended action.'], ['Key message', 'Define the takeaway in one sentence; foreground it, reconnect throughout, and state it again at the close.'], ['Logical structure', 'Give enough background without overload; use titles and signposts so people know where they are going.'], ['Story & conversation', 'Use relevant stories, examples, and questions; speak to people naturally rather than reading a script.'], ['Voice & body', 'Be audible, articulate, varied, and well-paced; align eye contact, open gestures, movement, and pause.'], ['Visuals', 'Use few readable words and clear contrast; visuals serve the idea. The talk should still work without slides.']], rehearsal: ['Write and organise the message, then use notes as prompts rather than reading.', 'Rehearse in presentation clothing, venue, and real AV setup.', 'Record playback or use a mock audience to inspect time, voice, posture, and comprehension.', 'Arrive early and test microphone, projection, network, and backup slides.'], timing: 'When time is cut, remove inessential detail and protect key points and takeaway. Do not speed-read the original plan.', group: 'For group presentations, define who says what and allocate slides rather than vague themes; introduce members and hand off clearly between speakers.' },
    structures: { title: 'Rapid speaking: four reusable structures', intro: 'Structure helps the speaker organise and remember while helping the listener focus and recall. Match the framework to the purpose.', headers: ['Framework', 'Structure', 'Best fit'], rows: [['3-I', 'Issue → Illustration → Invitation', 'Dialogue, advice, rapport; illustrate with a story and invite response'], ['3-W', 'What? → So what? → Now what?', 'Teaching, persuasion, debate; define, show significance, give action'], ['PSB', 'Problem → Solution → Benefit', 'Formal proposal, demo, business/academic pitch; prove the solution'], ['PREP', 'Point → Reason → Example → Point', 'Impromptu answer and short speech; organise in 30 seconds']], prep: 'For a longer impromptu response, expand to P-R-E-R-E-P. Practise unfamiliar topics, record yourself, and inspect body language, pause, and tone.', narrative: 'General presentation spine: Tell them what you are going to tell them → Tell them → Tell them what you told them.' },
    ai: { title: 'Gen-AI: use the output, not an accountability escape hatch', intro: 'An LLM generates linguistically plausible continuation; it does not determine truth. Fluent, confident, citation-shaped output is not evidence.', concepts: [['Truth-indifference', 'The model may produce true or false content, but veracity is not central to generation; this is not intentional deception.'], ['Epistemic insouciance', 'A lack of concern for whether belief is reality-based and supported by the best evidence; for people, refusing inquiry is the risk.'], ['Minimal epistemic responsibility', 'If you claim to believe p, you should at least answer: What reasons do you have for believing p?'], ['Professional accountability', 'Putting AI content in a team report means the team endorses it; the generator cannot carry your ethical or professional duty.']], caseTitle: 'Mata v. Avianca: why asking the model to verify itself failed', caseSteps: [['1 · Generate', 'A lawyer used ChatGPT for legal research and cited multiple non-existent cases and quotations.'], ['2 · Reassure', 'He asked the same model whether the cases were real; it confidently confirmed them.'], ['3 · Submit', 'Fabricated names, dockets, judges, dates, and internal citations entered a formal court filing.'], ['4 · Detect', 'Opposing counsel and the judge could not find the cases in dockets or databases; the court considered sanctions.']], lesson: 'Self-verification is not independent verification. A model can repeat and strengthen its fabrication; professionals must return to authoritative databases, original documents, and traceable evidence.', checklist: ['Independently verify names, dates, statistics, quotations, laws, cases, and recommendations.', 'Open the original source and confirm it exists and supports the claim.', 'Record where AI was used and what humans changed and approved.', 'Consider how data, prompt, omission, and bias shaped the output.', 'State uncertainty when evidence is weak; do not convert plausibility into fact.', 'Form belief according to evidence and explain the reason to client, team, or public.'] },
    review: { title: 'Six memory lines + twelve self-checks', intro: 'Remember success conditions, then select the communication form for the scenario. Select a question to reveal the answer.', memory: [['Meeting filter', 'Need interaction / decision? If no → async'], ['Agenda', 'Objective · Question · Time · Owner · Process · Pre-work'], ['Chair', 'Business · Inclusion · Decision · Difficulty'], ['Minutes', 'Outcome · Reason · Action · Owner · Due'], ['Speaking', '3-I · 3-W · PSB · PREP'], ['AI', 'Plausible ≠ true · Verify independently · Human accountable']], quiz: [['When should you not call a meeting?', 'When it is a one-way update, needs no immediate action, or can be solved by two people; use email, chat, a shared document, or direct contact.'], ['What must an effective agenda tell participants?', 'Objective, question, priority/time, item owner, discussion/decision process, pre-work, and expected outcome.'], ['Why is the chair not the person who speaks most?', 'The chair manages process, time, participation, and decisions; using the role to suppress views defeats the meeting.'], ['Why can silence not be treated as agreement?', 'People may be nervous, interrupted, in a minority, or unclear about process; actively confirm and invite unheard voices.'], ['What is the critical action information in minutes?', 'What, responsible person, due date, and the decision and rationale needed to understand the task.'], ['What is needed before recording and what is the risk?', 'Get permission; recording may make people guarded, reduce candour, and increase formality.'], ['Why remove report-outs from virtual meetings?', 'Written pre-reads handle updates; synchronous time should support questions, problem-solving, and judgement.'], ['When is an Ad Hoc meeting justified?', 'For an urgent operational or relationship crisis where waiting expands loss; still use purpose, timebox, small attendance, and action.'], ['What should you do when presentation time is suddenly cut?', 'Remove inessential detail and protect the key message, key points, and takeaway; do not simply speak faster.'], ['What are the four PREP steps?', 'Point → Reason → Example → Point reiterated.'], ['Why is asking the same LLM to verify its citations insufficient?', 'It can repeat and reinforce the same fabrication; verification must use independent, authoritative, traceable sources.'], ['What does minimal epistemic responsibility require?', 'At minimum, explain the reasons and relevant evidence for what you claim to believe—not merely “the AI said so.”']] },
    sourcesTitle: 'Own-time material index', sourcesIntro: 'This page covers all 14 materials in the folder. Public articles link to originals; course PDFs and the Panopto transcript are not published as downloadable source files.', sourceBoundary: 'Meeting and presentation advice must be adapted to purpose, audience, and risk. Statistics illustrate the source’s problem scale and should not be generalised without source and date.',
  },
} as const

export default function Week01({ locale }: { locale: Locale }) {
  const c = copy[locale]
  const ids = ['map', 'design', 'chair', 'minutes', 'formats', 'presentation', 'structures', 'ai', 'review', 'sources']
  const toc = ids.map((id, index) => ({ id, label: c.toc[index] }))
  return (
    <WeekLayout weekId="01" locale={locale} eyebrow="Week 01 · Professional communication" title={c.title} subtitle={c.subtitle} summary={c.summary} updated="04 Sep 2026" tags={[...c.tags]} toc={toc}>
      <ContentSection id="map" index="01" title={c.map.title} intro={c.map.intro}><LeadCard label={locale === 'zh' ? '工作主线' : 'Working sequence'}>{c.map.lead}</LeadCard><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{c.map.cards.map(([title, body], index) => <InfoCard key={title} title={title} tone={index % 3 === 0 ? 'blue' : index % 3 === 1 ? 'accent' : 'warm'}>{body}</InfoCard>)}</div><Callout label={locale === 'zh' ? '共同指标' : 'Common measure'}>{c.map.rule}</Callout></ContentSection>
      <ContentSection id="design" index="02" title={c.design.title} intro={c.design.intro}><div className="grid gap-3 md:grid-cols-2 lg:grid-cols-4">{c.design.filters.map(([title, body]) => <InfoCard key={title} title={title} tone="accent">{body}</InfoCard>)}</div><div className="mt-4"><ResponsiveTable headers={[...c.design.agendaHeaders]} rows={c.design.agendaRows.map((row) => [...row])} /></div><InfoCard title={locale === 'zh' ? '会前准备' : 'Preparation'} tone="blue" className="mt-4"><ul className="list-disc space-y-2 pl-5">{c.design.preparation.map((item) => <li key={item}>{item}</li>)}</ul></InfoCard><Callout label="Structure ≠ power">{c.design.power}</Callout></ContentSection>
      <ContentSection id="chair" index="03" title={c.chair.title} intro={c.chair.intro}><InfoCard title={locale === 'zh' ? '开场之前与开场时' : 'Before and at the opening'} tone="accent"><ul className="list-disc space-y-2 pl-5">{c.chair.before.map((item) => <li key={item}>{item}</li>)}</ul></InfoCard><div className="mt-4 grid gap-3 md:grid-cols-2">{c.chair.four.map(([title, body], index) => <InfoCard key={title} title={`${index + 1} · ${title}`} tone={index === 3 ? 'coral' : 'plain'}>{body}</InfoCard>)}</div><Callout label={locale === 'zh' ? '成员责任' : 'Member responsibility'}>{c.chair.member}</Callout></ContentSection>
      <ContentSection id="minutes" index="04" title={c.minutes.title} intro={c.minutes.intro}><div className="grid gap-3 md:grid-cols-2 lg:grid-cols-3">{c.minutes.items.map(([title, body]) => <InfoCard key={title} title={title} tone="accent">{body}</InfoCard>)}</div><Callout label={locale === 'zh' ? '录音边界' : 'Recording boundary'}>{c.minutes.recording}</Callout><h3 className="mb-4 mt-8 text-2xl font-black">{locale === 'zh' ? '如何判断会议是否有效' : 'How to measure meeting effectiveness'}</h3><div className="grid gap-3 md:grid-cols-2 lg:grid-cols-4">{c.minutes.metrics.map(([title, body]) => <InfoCard key={title} title={title}>{body}</InfoCard>)}</div></ContentSection>
      <ContentSection id="formats" index="05" title={c.formats.title} intro={c.formats.intro}><ResponsiveTable headers={[...c.formats.decisionHeaders]} rows={c.formats.decisionRows.map((row) => [...row])} /><div className="mt-4 grid gap-4 lg:grid-cols-3"><InfoCard title="Ad Hoc" tone="coral"><ul className="list-disc space-y-2 pl-5">{c.formats.adHoc.map((item) => <li key={item}>{item}</li>)}</ul></InfoCard><InfoCard title={locale === 'zh' ? 'Virtual · 会前' : 'Virtual · Before'} tone="blue"><ul className="list-disc space-y-2 pl-5">{c.formats.virtualBefore.map((item) => <li key={item}>{item}</li>)}</ul></InfoCard><InfoCard title={locale === 'zh' ? 'Virtual · 会中与结束' : 'Virtual · During and close'} tone="accent"><ul className="list-disc space-y-2 pl-5">{c.formats.virtualDuring.map((item) => <li key={item}>{item}</li>)}</ul></InfoCard></div></ContentSection>
      <ContentSection id="presentation" index="06" title={c.presentation.title} intro={c.presentation.intro}><div className="grid gap-3 md:grid-cols-2 lg:grid-cols-3">{c.presentation.principles.map(([title, body], index) => <InfoCard key={title} title={title} tone={index % 2 ? 'plain' : 'warm'}>{body}</InfoCard>)}</div><div className="mt-4 grid gap-4 lg:grid-cols-2"><InfoCard title={locale === 'zh' ? '排练与技术' : 'Rehearsal and technology'} tone="accent"><ul className="list-disc space-y-2 pl-5">{c.presentation.rehearsal.map((item) => <li key={item}>{item}</li>)}</ul></InfoCard><div className="grid gap-4"><InfoCard title={locale === 'zh' ? '时间被压缩' : 'When time is cut'} tone="coral">{c.presentation.timing}</InfoCard><InfoCard title={locale === 'zh' ? '小组演示' : 'Group presentation'} tone="blue">{c.presentation.group}</InfoCard></div></div></ContentSection>
      <ContentSection id="structures" index="07" title={c.structures.title} intro={c.structures.intro}><ResponsiveTable headers={[...c.structures.headers]} rows={c.structures.rows.map((row) => [...row])} /><div className="mt-4 grid gap-4 md:grid-cols-2"><InfoCard title="PREP practice" tone="accent">{c.structures.prep}</InfoCard><InfoCard title={locale === 'zh' ? '通用演示骨架' : 'General presentation spine'} tone="blue">{c.structures.narrative}</InfoCard></div></ContentSection>
      <ContentSection id="ai" index="08" title={c.ai.title} intro={c.ai.intro}><div className="grid gap-3 md:grid-cols-2">{c.ai.concepts.map(([title, body]) => <InfoCard key={title} title={title} tone="coral">{body}</InfoCard>)}</div><h3 className="mb-4 mt-9 text-2xl font-black">{c.ai.caseTitle}</h3><div className="grid gap-3 md:grid-cols-2 lg:grid-cols-4">{c.ai.caseSteps.map(([title, body]) => <InfoCard key={title} title={title} tone="warm">{body}</InfoCard>)}</div><Callout label="Self-verification ≠ verification">{c.ai.lesson}</Callout><InfoCard title={locale === 'zh' ? '专业核验清单' : 'Professional verification checklist'} tone="accent" className="mt-4"><ul className="list-disc space-y-2 pl-5">{c.ai.checklist.map((item) => <li key={item}>{item}</li>)}</ul></InfoCard></ContentSection>
      <ContentSection id="review" index="09" title={c.review.title} intro={c.review.intro}><div className="mb-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{c.review.memory.map(([title, body]) => <InfoCard key={title} title={title} tone="accent">{body}</InfoCard>)}</div><QuizAccordion items={c.review.quiz.map(([question, answer]) => ({ question, answer }))} /></ContentSection>
      <ContentSection id="sources" index="10" title={c.sourcesTitle} intro={c.sourcesIntro}><div className="grid gap-2 sm:grid-cols-2">{sourceItems.map(([title, label, url]) => url ? <a key={title} href={url} target="_blank" rel="noreferrer" className="group rounded-xl border bg-card px-4 py-3 transition-colors hover:bg-[var(--week-accent-soft)]"><span className="flex items-center justify-between gap-3 text-sm font-bold">{title}<ExternalLink className="size-3.5 text-muted-foreground group-hover:text-foreground" /></span><span className="mt-1 block text-xs text-muted-foreground">{label}</span></a> : <div key={title} className="rounded-xl border bg-card px-4 py-3"><span className="text-sm font-bold">{title}</span><span className="mt-1 block text-xs text-muted-foreground">{label}</span></div>)}</div><Callout label={locale === 'zh' ? '使用边界' : 'Use boundary'}>{c.sourceBoundary}</Callout></ContentSection>
    </WeekLayout>
  )
}
