import { ExternalLink } from 'lucide-react'
import { QuizAccordion } from '@/components/quiz-accordion'
import { Callout, ContentSection, InfoCard, LeadCard, ResponsiveTable, WeekLayout } from '@/components/week-layout'
import multiculturalSuccess from '@/assets/week04-multicultural-success.jpg'
import type { Locale } from '@/i18n'

const sourceItems = [
  ['Getting Cross-Cultural Teamwork Right', 'Harvard Business Review · Tsedal Neeley · 2014', 'https://hbr.org/2014/09/getting-cross-cultural-teamwork-right'],
  ['Developmental Model of Intercultural Sensitivity', 'IDRInstitute · revised 2025', 'https://www.idrinstitute.org/dmis/'],
  ['High Context Culture vs Low Context Culture', 'TechTello study summary', 'https://www.techtello.com/high-context-culture-vs-low-context-culture/'],
  ['Conflict Styles and High-Low Context Cultures', 'Croucher et al. · Communication Research Reports · 2012', 'https://doi.org/10.1080/08824096.2011.640093'],
  ['FIT5122 Cross Cultural Communication Issues', 'Course PDF · 3 pages', null],
  ['Navigating Global Collaboration', 'Course PDF · 3 pages', null],
  ['The Role of Cultural Interpreters', 'Course PDF · 2 pages', null],
  ['Cross Cultural Awareness', 'Course transcript · 11:10', null],
  ['Intercultural Differences', 'Course transcript · 7:29', null],
  ['Intercultural Strategies', 'Course transcript · 8:39', null],
  ['Multicultural Success', 'Course transcript · 1:44', null],
  ['Mastering Global IT Teams', 'Course visual', null],
] as const

const copy = {
  zh: {
    title: 'Cross-Cultural Collaboration', subtitle: '从文化差异到团队优势',
    summary: '文化差异既可能造成误读、冲突与项目断裂，也能扩大创造力、知识迁移和市场洞察。关键不是消除差异，而是发展感知、理解和桥接差异的能力。',
    tags: ['12 份 own-time 材料', 'DMIS 六阶段', '四国研究 N=1,792', '10 道自测'],
    toc: ['多元团队价值', 'DMIS', '语境与时间', '冲突研究', 'Triple-M', '文化中介', '团队 Playbook', '速记自测', '材料索引'],
    value: {
      title: '差异可以是风险，也可以是资源', intro: '多元团队不会自动高绩效；只有在成员能听见、理解并整合差异时，潜力才会转化为结果。',
      lead: '不要把自己的文化当作默认操作系统。先观察差异，再解释差异，最后共同设计工作方式。',
      benefits: [['Creativity 创造力', '不同成员能“换一种做法、换一个角度看”，突破本地习惯和过去失败的限制。'], ['Learning & unlearning', '观点交换带来知识迁移，也帮助团队放下已经不再适用的做法。'], ['Leadership & process', '组合不同领导与工作方式，可以同时获得关系建设、效率和创新。'], ['Conflict options', '更多问题视角和冲突处理方式，有助于解决长期僵局。'], ['Market awareness', '不同文化经验能发现目标市场的隐含需求和风险。'], ['Belonging & morale', '当少数观点被认真听见，成员更有归属感，团队士气和参与度提高。']],
      warning: '文化差异也会造成沟通断裂、方法冲突和失败。Diversity 是输入；inclusion、shared process 和 cultural competence 才把它转化为价值。',
    },
    dmis: {
      title: 'DMIS：感知文化差异的六个位置', intro: 'Bennett 的模型描述人们如何组织“我们/他们”的文化差异经验：从以自身文化为现实中心，发展到把所有文化理解为相对于情境。',
      ethnocentric: 'Ethnocentrism · 自身文化是现实中心', ethnorelative: 'Ethnorelativism · 文化相对于情境',
      stages: [['Denial 否认', '几乎看不见文化差异，只用“外国人”等宽泛类别，或回避跨文化接触。'], ['Defense 防御', '以刻板、两极的 us/them 方式理解差异，通常认为“我们”更优；reversal 只是把优劣两极倒转。'], ['Minimization 最小化', '把自己的价值和经验当作普遍真理；“大家都一样”会遮蔽深层差异与主流文化特权。'], ['Acceptance 接受', '承认其他文化同样复杂并保持好奇与尊重；接受不等于同意，也还不代表能自如改变行为。'], ['Adaptation 适应', '通过 intercultural empathy 生成符合另一情境的真实行为，并有意识地调整沟通方式。'], ['Integration 整合', '能在多个文化世界观之间移动，把文化 liminality 用于搭桥和复杂调解。']],
      modelNote: '2025 修订说明：一个位置通常占主导，策略可能横跨多个位置；发展方向被视为单向且持久，但可能出现 retreat。熟悉某个国家会扩大可实践范围，不自动改变敏感度层级。',
      exam: '最容易混淆：Minimization 看似包容，却以“同一标准”抹掉差异；Acceptance 形成尊重，Adaptation 才把尊重转化为行为能力；Integration 也不是每项跨文化任务的必要条件。',
    },
    context: {
      title: 'High / Low Context 与时间观', intro: '这些模型描述相对偏好，不是国籍决定的个人定律。正确用法是提出待验证的假设，再向真实成员澄清。',
      headers: ['维度', 'High-context 倾向', 'Low-context 倾向', '团队误读'],
      rows: [['信息位置', '关系、共同背景、语气、停顿、表情与暗示', '意义放在明确、详细、可记录的语言中', '间接被看作模糊；直接被看作冒犯或不信任'], ['回答方式', '为避免冒犯，maybe/possibly 可能实际表示 no；yes 可能只表示“听见了”', '按字面理解并期待清楚的 yes/no', '听到同一个词却得到不同承诺'], ['冲突', '分歧较个人化，偏好 avoiding / obliging 等非对抗方式', '把问题与人分开，更接受直接、dominating 的处理', '沉默被误读为同意；直接挑战被误读为霸凌'], ['规则', '许多规范隐含并被视为理所当然', '偏好明确规则、标准和书面确认', '一方看见“常识”，另一方看见信息缺失'], ['权威与反馈', '重视层级、面子与公开场合的尊重', '较接受直接反馈与扁平讨论', '公开纠正可能令成员失去面子或退出']],
      timeHeaders: ['时间取向', '典型重点', '可能贡献', '可能摩擦'], timeRows: [['Monochronic 单时', '计划、准时、一次一事、按期限完成', '清晰节奏、效率、可预测性', '可能低估关系建设与突发情境'], ['Polychronic 多时', '关系、多人多事、交易完成、时间弹性', '适应变化、关系与多任务', '可能被理解为拖延或不尊重 deadline']],
      practice: '跨风格沟通：先识别自己的默认值；对 high-context 多听意图和非语言线索并确认理解；对 low-context 清楚说主旨、责任和期限；共同约定书面记录和升级规则。',
    },
    research: {
      title: '四国研究：文化影响冲突偏好，但不是简单二分', intro: 'Croucher 等人以 Oetzel 38-item Conflict Style Instrument 比较四国样本；结果支持部分理论，也反驳“high/low context 足以解释一切”。',
      samples: [['India', '657'], ['Ireland', '311'], ['Thailand', '232'], ['United States', '592']], total: '总样本 N = 1,792',
      findings: [['Avoiding', 'India 与 Thailand 的偏好高于 Ireland 与 United States。'], ['Obliging', 'High-context 两国整体高于 low-context 两国。'], ['Dominating', 'Ireland 与 United States 高于 India 与 Thailand。'], ['Compromising', 'India 与 Thailand 反而高于两个 low-context 国家。'], ['Integrating', '不是 high/low 二分：India 最高、Ireland 第二、Thailand 第三、United States 最低。']],
      significance: '五种冲突风格都出现显著 national-culture effect（各项 p < .0001），但国家内部差异与风格交叉说明模型只能表达群体倾向。',
      limits: ['Ireland 样本主要来自 Dublin，Thailand 主要来自 Bangkok，不能代表整个国家。', '样本量不等，研究采用 Games-Howell post hoc；结论仍应关注实际效应与情境。', '冲突偏好采用 self-report，未必等于真实行为。', 'Group-level tendency 不能直接变成对某个队友的判断；个人经历、职业环境与变化中的社会经济都会影响行为。'],
    },
    triple: {
      title: 'Triple-M：Learn → Understand → Teach', intro: '跨文化共同点不是一次培训后获得，而是通过三种相互强化的活动持续建构。',
      items: [['Mutual Learning · 学习', '发现别人做什么。Absorb：观察行为线索；Ask：用敏感且具体的问题补足语境；Relate：建立个人连接、同理心与信任。'], ['Mutual Understanding · 理解', '追问为什么这样做。暂停判断，反思自己的偏见，接受 ambiguity，在推断意图或动机前收集更多信息。'], ['Mutual Teaching · 教学', '帮助彼此理解规范。Instruct：解释规则与期待；Facilitate：作为中介预见误读、翻译细微差异并引导共同理解。']],
      loop: 'Absorbing 产生更好的问题，Asking 加深理解，Relating 提供更多观察机会；理解又让成员采用更合适的新行为。这是迭代循环，不是一次性清单。',
      trust: '共同目标与个人连接建立 trust。成员愿意分享适应新规范的风险和脆弱性，跨文化协作的 playing field 才更平等。',
    },
    broker: {
      title: 'Cultural Broker：做团队的“Human API”', intro: '文化中介不是替别人发言，而是解释底层 context、values 与 norms，让双方能直接理解并继续合作。',
      functions: [['解码沟通', '说明 yes 可能是“我听见了”、沉默可能是尊重或犹豫，并澄清俚语与行业术语。'], ['建立安全与信任', '让少数成员安全表达，及早发现 hidden conflict，并对齐直接/含蓄反馈。'], ['优化决策', '平衡层级期待、带回安静成员的观点，并协调 certainty 与 ambiguity 的风险偏好。']],
      traits: ['较高 CQ、同理心和暂停判断的能力。', '双文化或多文化的生活、学习或工作经验。', '主动倾听、重述、澄清和调解能力。', '能被不同群体自然信任，同时不把自己变成唯一沟通通道。'],
      identify: '留意自然的 bridge builders：成员会向其咨询；他们能发现 disengagement、重述争论并帮助对方重新进入讨论。',
      debugger: '课程比喻：文化中介像 human debugger。看到沉默或误解时，不“删除错误的人”，而是逐步检查形成该行为的文化逻辑。',
    },
    playbook: {
      title: '把文化敏感度写进团队系统', intro: '不要只期待成员“更包容”。把可执行规则写进 Social Contract、会议、任务和决策流程。',
      actions: [['Communication', '选择所有人可访问的共同渠道与语言；避免 slang；重要决定书面确认。'], ['Decision & conflict', '预先约定如何决策、表达异议、升级冲突和记录 dissent。'], ['Tasks', '任务定义清楚，说明是个人负责还是全员共同贡献，并保持可见。'], ['Time', '把 deadline、会议准时与关系建设都显性安排，不把单时或多时风格当作不专业。'], ['Inclusive meetings', '使用 structured speaking turns、会前书面意见和逐人确认，避免安静成员的洞见丢失。'], ['Feedback', '训练直接但尊重的批评，并把过度含蓄的意见变成可执行信息。'], ['Motivation', '不要假设所有人由同一奖励驱动；了解成长、认可、收入与工作满足等差异。'], ['Learning system', '进行 context mapping、文化情境角色扮演、团队 charter 回顾与持续复盘。']],
      final: '专业目标不是预测“某国人会怎样”，而是设计一个能让成员澄清、适应、表达和共同负责的系统。',
    },
    review: {
      title: '九组速记 + 十题自测', intro: '先记模型边界，再做情境判断。点击问题展开答案。',
      memory: [['DMIS', 'Denial → Defense → Minimization → Acceptance → Adaptation → Integration'], ['AAR', 'Absorb → Ask → Relate'], ['Triple-M', 'Mutual Learning → Understanding → Teaching'], ['Context', 'High：意义在关系与暗示；Low：意义在明确文字'], ['Time', 'Monochronic：计划与期限；Polychronic：关系与弹性'], ['Broker', 'Decode · Bridge · Facilitate']],
      quiz: [['DMIS 中 ethnocentric 与 ethnorelative 各包含哪些阶段？', 'Ethnocentric：Denial、Defense、Minimization；Ethnorelative：Acceptance、Adaptation、Integration。'], ['为什么“我们都一样”可能属于 Minimization 而不是高文化敏感度？', '它把自身价值当作普遍标准，遮蔽深层差异和主流文化特权。'], ['Acceptance 与 Adaptation 有什么区别？', 'Acceptance 尊重并认识差异；Adaptation 能用 intercultural empathy 生成适合另一情境的行为。'], ['High-context 的 yes 为什么不能自动当作承诺？', '它可能只表示“我听见了”或为了避免直接冒犯；需要确认具体行动与期限。'], ['Monochronic 与 Polychronic 团队如何减少 deadline 冲突？', '共同显性约定时间窗、优先级、关系活动、变更通知与书面责任，而不是互贴“不尊重”或“僵化”标签。'], ['四国研究最支持哪些 high/low-context 预测？', 'India/Thailand 更偏 avoiding、obliging；Ireland/US 更偏 dominating。'], ['为什么 integrating 结果反对简单二分？', '排序为 India、Ireland、Thailand、US，并没有按 high/low 两组排列。'], ['为什么不能用研究结果判断某个队友？', '样本是群体平均且有地域、自陈局限；个人经验、职业与具体情境会改变行为。'], ['Triple-M 中 learning、understanding、teaching 分别问什么？', 'Learning：别人做什么；Understanding：为什么；Teaching：如何帮助双方解释规范并建立共同做法。'], ['怎样避免 Cultural Broker 变成团队单点故障？', '让其促进双方直接沟通，并通过训练、共同规则与 shared CQ 把桥接能力扩散到全队。']],
    },
    sourcesTitle: 'Own-time 材料索引', sourcesIntro: '本页覆盖目录中所有 12 份有效材料；公开来源链接原站，课程 PDF、字幕和转录不上传。', sourceBoundary: '文化模型用于解释可能的相对偏好，不用于按国籍预测个人。研究证据应连同样本、方法与局限一起使用。',
  },
  en: {
    title: 'Cross-Cultural Collaboration', subtitle: 'Turn cultural difference into team strength',
    summary: 'Cultural difference can cause misreading, conflict, and project fracture—or expand creativity, knowledge transfer, and market insight. The goal is not to erase difference, but to perceive, understand, and bridge it.',
    tags: ['12 own-time materials', '6 DMIS positions', 'Four-country study N=1,792', '10 self-checks'], toc: ['Value of diversity', 'DMIS', 'Context & time', 'Conflict evidence', 'Triple-M', 'Cultural brokers', 'Team playbook', 'Review', 'Sources'],
    value: { title: 'Difference is both risk and resource', intro: 'A diverse team does not become high-performing automatically; potential becomes results only when members can hear, understand, and integrate difference.', lead: 'Do not treat your culture as the default operating system. Observe difference, investigate its logic, then co-design the way of working.', benefits: [['Creativity', 'Different ways of doing and viewing help a team escape local habits and lessons from past failure.'], ['Learning & unlearning', 'Exchange transfers knowledge and helps the team release practices that no longer fit.'], ['Leadership & process', 'Combining work and leadership styles can balance relationships, efficiency, and innovation.'], ['Conflict options', 'More perspectives and conflict approaches can unlock stubborn problems.'], ['Market awareness', 'Cultural experience surfaces hidden needs and risks in target markets.'], ['Belonging & morale', 'When minority perspectives are heard, belonging, morale, and participation improve.']], warning: 'Cultural difference can also fracture communication and method. Diversity is an input; inclusion, shared process, and cultural competence turn it into value.' },
    dmis: { title: 'DMIS: six positions for experiencing difference', intro: 'Bennett’s model describes how people organise cultural us/other experience—from one’s own culture as central to reality to cultures as relative to context.', ethnocentric: 'Ethnocentrism · one culture is central', ethnorelative: 'Ethnorelativism · cultures are relative to context', stages: [['Denial', 'Difference is barely perceived, reduced to broad categories such as “foreigner,” or avoided.'], ['Defense', 'Difference is stereotyped and polarised into us/them, usually with us superior; reversal only swaps the poles.'], ['Minimization', 'One’s own values and experience are treated as universal; “we are all the same” can hide deep difference and privilege.'], ['Acceptance', 'Other cultures are recognised as equally complex with curiosity and respect; acceptance is not agreement or behavioural fluency.'], ['Adaptation', 'Intercultural empathy generates authentic behaviour appropriate to another context and intentional communication change.'], ['Integration', 'A person moves among cultural worldviews and uses cultural liminality for bridging and sophisticated mediation.']], modelNote: 'The 2025 revision says one position is predominant while strategies may span positions; movement is treated as one-way and durable, with possible retreats. Familiarity broadens what can be enacted but does not itself change sensitivity level.', exam: 'Key distinctions: Minimization can sound inclusive while erasing difference; Acceptance respects difference; Adaptation converts respect into competent action; Integration is not required for every intercultural task.' },
    context: { title: 'High / Low Context and orientations to time', intro: 'These are relative tendencies, not national laws for individuals. Use them to form a hypothesis, then clarify with the actual person.', headers: ['Dimension', 'High-context tendency', 'Low-context tendency', 'Likely team misreading'], rows: [['Where meaning lives', 'Relationships, shared background, tone, pauses, expression, implication', 'Explicit, detailed, recordable words', 'Indirect seems vague; direct seems rude or distrustful'], ['Answers', 'Maybe can mean no; yes can mean “I hear you”', 'Literal interpretation and clear yes/no expected', 'The same word creates different commitments'], ['Conflict', 'Disagreement feels personal; avoiding/obliging and non-confrontation', 'Problem separated from person; direct/dominating more acceptable', 'Silence becomes consent; challenge becomes bullying'], ['Rules', 'Many norms are implicit and taken for granted', 'Rules, standards, and written confirmation preferred', 'Common sense to one side is missing information to the other'], ['Authority & feedback', 'Hierarchy, face, and public respect matter', 'Direct feedback and flatter discussion accepted', 'Public correction causes loss of face or withdrawal']], timeHeaders: ['Time orientation', 'Primary emphasis', 'Potential contribution', 'Potential friction'], timeRows: [['Monochronic', 'Plans, punctuality, one task, deadlines', 'Clear pace, efficiency, predictability', 'May undervalue relationships and disruption'], ['Polychronic', 'Relationships, many tasks, completing interactions, flexible time', 'Adaptability, relationship building, multitasking', 'May be read as delay or disrespect for deadlines']], practice: 'Across styles: identify your default; with high-context communication listen for intent and non-verbal cues, then confirm; with low-context communication state the point, owner, and deadline; agree how decisions are recorded and escalated.' },
    research: { title: 'Four-country evidence: culture matters, but not as a simple binary', intro: 'Croucher et al. used Oetzel’s 38-item Conflict Style Instrument across four national samples. Findings support part of the theory while rejecting the idea that high/low context explains everything.', samples: [['India', '657'], ['Ireland', '311'], ['Thailand', '232'], ['United States', '592']], total: 'Total sample N = 1,792', findings: [['Avoiding', 'India and Thailand scored higher than Ireland and the United States.'], ['Obliging', 'The two high-context nations scored higher overall.'], ['Dominating', 'Ireland and the United States scored higher than India and Thailand.'], ['Compromising', 'India and Thailand also scored higher than the low-context nations.'], ['Integrating', 'Not a high/low binary: India first, Ireland second, Thailand third, United States fourth.']], significance: 'National culture had a significant effect on all five styles (all p < .0001), yet within-group variation and cross-pattern results mean these are group tendencies only.', limits: ['Irish data were concentrated around Dublin and Thai data around Bangkok; neither represents an entire nation.', 'Sample sizes differed and Games-Howell post hoc comparisons were used; context and effect size still matter.', 'Conflict preferences were self-reported and may not equal behaviour.', 'A group average cannot diagnose a teammate; lived experience, profession, and changing economies also shape behaviour.'] },
    triple: { title: 'Triple-M: Learn → Understand → Teach', intro: 'Cross-cultural common ground is not delivered by one training session. It is built through three mutually reinforcing activities.', items: [['Mutual Learning', 'Discover what others do. Absorb behavioural cues, Ask sensitive and focused questions, and Relate personally to build empathy and trust.'], ['Mutual Understanding', 'Investigate why. Suspend judgement, reflect on your own bias, accept ambiguity, and gather information before inferring intent.'], ['Mutual Teaching', 'Help both sides understand norms. Instruct expectations and Facilitate as an intermediary who anticipates and translates misreading.']], loop: 'Absorbing creates better questions; Asking deepens understanding; Relating creates more observation. Understanding then supports appropriate new behaviour. This is an iterative loop, not a checklist.', trust: 'Shared goals and personal connection build trust. When members can share the risk and vulnerability of adaptation, the collaborative playing field becomes more equal.' },
    broker: { title: 'Cultural Broker: the team’s “Human API”', intro: 'A broker does not speak instead of others. They explain underlying context, values, and norms so both sides can understand each other and keep collaborating.', functions: [['Decode communication', 'Explain when yes means “I hear you,” when silence signals respect or hesitation, and clarify idioms and jargon.'], ['Build safety and trust', 'Make minority voices safer, detect hidden conflict, and align blunt and indirect feedback.'], ['Improve decisions', 'Balance hierarchy expectations, recover quieter perspectives, and reconcile certainty versus ambiguity.']], traits: ['Cultural intelligence, empathy, and the ability to suspend judgement.', 'Bicultural or multicultural lived, study, or work experience.', 'Active listening, reframing, clarification, and mediation skill.', 'Trusted across groups without becoming the only communication channel.'], identify: 'Look for natural bridge builders: people others ask for advice, who notice disengagement, rephrase disagreements, and bring colleagues back in.', debugger: 'The course analogy is a human debugger. When silence or misunderstanding appears, do not “delete the faulty person”; step through the cultural logic that produced the behaviour.' },
    playbook: { title: 'Build cultural sensitivity into the team system', intro: 'Do not merely ask people to “be inclusive.” Put executable rules into the Social Contract, meetings, tasks, and decisions.', actions: [['Communication', 'Choose a shared language and accessible channel; avoid slang; confirm important decisions in writing.'], ['Decision & conflict', 'Agree how to decide, dissent, escalate conflict, and record disagreement.'], ['Tasks', 'Define work clearly, including whether ownership is individual or collaborative, and keep progress visible.'], ['Time', 'Schedule deadlines, punctuality, and relationship-building explicitly; do not label one time style unprofessional.'], ['Inclusive meetings', 'Use structured turns, pre-meeting written input, and individual confirmation so quieter insight is not lost.'], ['Feedback', 'Practise direct but respectful critique and convert vague feedback into action.'], ['Motivation', 'Do not assume one motivator; explore growth, recognition, pay, and job satisfaction.'], ['Learning system', 'Use context mapping, cultural simulations, team-charter reviews, and retrospectives.']], final: 'The professional goal is not to predict how “people from a country” behave. It is to design a system where members clarify, adapt, speak, and share accountability.' },
    review: { title: 'Six memory lines + ten self-checks', intro: 'Remember model boundaries first, then make contextual judgements. Select a question to reveal the answer.', memory: [['DMIS', 'Denial → Defense → Minimization → Acceptance → Adaptation → Integration'], ['AAR', 'Absorb → Ask → Relate'], ['Triple-M', 'Mutual Learning → Understanding → Teaching'], ['Context', 'High: meaning in relation and implication; Low: meaning in explicit words'], ['Time', 'Monochronic: schedule; Polychronic: relationship and flexibility'], ['Broker', 'Decode · Bridge · Facilitate']], quiz: [['Which DMIS positions are ethnocentric and which are ethnorelative?', 'Ethnocentric: Denial, Defense, Minimization. Ethnorelative: Acceptance, Adaptation, Integration.'], ['Why can “we are all the same” indicate Minimization rather than sensitivity?', 'It treats one’s own values as universal, hiding deep difference and dominant-culture privilege.'], ['How do Acceptance and Adaptation differ?', 'Acceptance recognises and respects difference; Adaptation uses intercultural empathy to generate appropriate behaviour.'], ['Why is a high-context yes not automatically a commitment?', 'It may mean “I hear you” or avoid direct offence; confirm the specific action and deadline.'], ['How can monochronic and polychronic teammates reduce deadline conflict?', 'Make time windows, priorities, relationship activities, change notices, and written ownership explicit rather than applying personal labels.'], ['Which predictions did the four-country study most strongly support?', 'India/Thailand preferred avoiding and obliging more; Ireland/US preferred dominating more.'], ['Why does the integrating result reject a simple binary?', 'The order was India, Ireland, Thailand, United States—not two high/low groups.'], ['Why can the results not diagnose an individual teammate?', 'They are group averages with geographic and self-report limits; individual experience, profession, and context vary.'], ['What does each Triple-M activity ask?', 'Learning asks what; Understanding asks why; Teaching helps both sides explain norms and build a shared practice.'], ['How do you stop a Cultural Broker becoming a single point of failure?', 'Use the broker to enable direct communication, then spread the skill through training, shared rules, and group CQ.']] },
    sourcesTitle: 'Own-time material index', sourcesIntro: 'This page covers all 12 valid materials in the folder. Public sources link to their originals; course PDFs, captions, and transcripts are not uploaded.', sourceBoundary: 'Cultural models explain possible relative tendencies; they do not predict individuals by nationality. Use research together with its sample, method, and limitations.',
  },
} as const

export default function Week04({ locale }: { locale: Locale }) {
  const c = copy[locale]
  const ids = ['value', 'dmis', 'context', 'research', 'triple', 'broker', 'playbook', 'review', 'sources']
  const toc = ids.map((id, index) => ({ id, label: c.toc[index] }))
  return (
    <WeekLayout weekId="04" locale={locale} eyebrow="Week 04 · Cross-cultural teamwork" title={c.title} subtitle={c.subtitle} summary={c.summary} updated="04 Sep 2026" tags={[...c.tags]} toc={toc}>
      <ContentSection id="value" index="01" title={c.value.title} intro={c.value.intro}><LeadCard label={locale === 'zh' ? '核心原则' : 'Core principle'}>{c.value.lead}</LeadCard><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{c.value.benefits.map(([title, body], index) => <InfoCard key={title} title={title} tone={index % 3 === 0 ? 'blue' : index % 3 === 1 ? 'accent' : 'warm'}>{body}</InfoCard>)}</div><Callout label={locale === 'zh' ? '关键边界' : 'Key boundary'}>{c.value.warning}</Callout><figure className="mt-5 overflow-hidden rounded-2xl border bg-card"><img src={multiculturalSuccess} alt="Roadmap for multicultural success in global IT teams" className="h-auto w-full" loading="lazy" /><figcaption className="px-4 py-3 text-xs text-muted-foreground">Mastering Global IT Teams · Week 04 own-time visual</figcaption></figure></ContentSection>
      <ContentSection id="dmis" index="02" title={c.dmis.title} intro={c.dmis.intro}><div className="grid gap-3 lg:grid-cols-2"><div><h3 className="mb-3 text-sm font-black uppercase tracking-wider text-[#c75f45]">{c.dmis.ethnocentric}</h3><div className="grid gap-3">{c.dmis.stages.slice(0, 3).map(([title, body]) => <InfoCard key={title} title={title} tone="coral">{body}</InfoCard>)}</div></div><div><h3 className="mb-3 text-sm font-black uppercase tracking-wider text-[var(--week-accent)]">{c.dmis.ethnorelative}</h3><div className="grid gap-3">{c.dmis.stages.slice(3).map(([title, body]) => <InfoCard key={title} title={title} tone="blue">{body}</InfoCard>)}</div></div></div><Callout label={locale === 'zh' ? '模型说明' : 'Model note'}>{c.dmis.modelNote}</Callout><Callout label="Exam clue">{c.dmis.exam}</Callout></ContentSection>
      <ContentSection id="context" index="03" title={c.context.title} intro={c.context.intro}><ResponsiveTable headers={[...c.context.headers]} rows={c.context.rows.map((row) => [...row])} /><div className="mt-4"><ResponsiveTable headers={[...c.context.timeHeaders]} rows={c.context.timeRows.map((row) => [...row])} /></div><Callout label={locale === 'zh' ? '实际做法' : 'In practice'}>{c.context.practice}</Callout></ContentSection>
      <ContentSection id="research" index="04" title={c.research.title} intro={c.research.intro}><LeadCard label={locale === 'zh' ? '研究设计' : 'Study design'}>{c.research.total}</LeadCard><div className="mt-4 grid grid-cols-2 gap-3 lg:grid-cols-4">{c.research.samples.map(([country, count]) => <InfoCard key={country} title={count} tone="blue">{country}</InfoCard>)}</div><div className="mt-4"><ResponsiveTable headers={[locale === 'zh' ? '冲突风格' : 'Conflict style', locale === 'zh' ? '研究结果' : 'Finding']} rows={c.research.findings.map((row) => [...row])} /></div><Callout label="Evidence">{c.research.significance}</Callout><InfoCard title={locale === 'zh' ? '研究局限' : 'Study limitations'} tone="warm" className="mt-4"><ul className="list-disc space-y-2 pl-5">{c.research.limits.map((item) => <li key={item}>{item}</li>)}</ul></InfoCard></ContentSection>
      <ContentSection id="triple" index="05" title={c.triple.title} intro={c.triple.intro}><div className="grid gap-4 lg:grid-cols-3">{c.triple.items.map(([title, body], index) => <InfoCard key={title} title={`${index + 1} · ${title}`} tone="accent">{body}</InfoCard>)}</div><Callout label={locale === 'zh' ? '迭代循环' : 'Iterative loop'}>{c.triple.loop}</Callout><InfoCard title="Trust & shared vulnerability" tone="blue" className="mt-4">{c.triple.trust}</InfoCard></ContentSection>
      <ContentSection id="broker" index="06" title={c.broker.title} intro={c.broker.intro}><div className="grid gap-4 md:grid-cols-3">{c.broker.functions.map(([title, body]) => <InfoCard key={title} title={title} tone="blue">{body}</InfoCard>)}</div><div className="mt-4 grid gap-4 lg:grid-cols-2"><InfoCard title={locale === 'zh' ? '关键特征' : 'Key characteristics'}><ul className="list-disc space-y-2 pl-5">{c.broker.traits.map((item) => <li key={item}>{item}</li>)}</ul></InfoCard><InfoCard title={locale === 'zh' ? '识别自然中介' : 'Identify natural interpreters'} tone="accent"><p>{c.broker.identify}</p><p className="mt-4 font-semibold text-foreground">{c.broker.debugger}</p></InfoCard></div></ContentSection>
      <ContentSection id="playbook" index="07" title={c.playbook.title} intro={c.playbook.intro}><div className="grid gap-3 md:grid-cols-2">{c.playbook.actions.map(([title, body], index) => <InfoCard key={title} title={`${String(index + 1).padStart(2, '0')} · ${title}`} tone={index % 2 ? 'plain' : 'accent'}>{body}</InfoCard>)}</div><div className="mt-4"><LeadCard label={locale === 'zh' ? '专业目标' : 'Professional goal'}>{c.playbook.final}</LeadCard></div></ContentSection>
      <ContentSection id="review" index="08" title={c.review.title} intro={c.review.intro}><div className="mb-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{c.review.memory.map(([title, body]) => <InfoCard key={title} title={title} tone="blue">{body}</InfoCard>)}</div><QuizAccordion items={c.review.quiz.map(([question, answer]) => ({ question, answer }))} /></ContentSection>
      <ContentSection id="sources" index="09" title={c.sourcesTitle} intro={c.sourcesIntro}><div className="grid gap-2 sm:grid-cols-2">{sourceItems.map(([title, label, url]) => url ? <a key={title} href={url} target="_blank" rel="noreferrer" className="group rounded-xl border bg-card px-4 py-3 transition-colors hover:bg-[var(--week-accent-soft)]"><span className="flex items-center justify-between gap-3 text-sm font-bold">{title}<ExternalLink className="size-3.5 text-muted-foreground group-hover:text-foreground" /></span><span className="mt-1 block text-xs text-muted-foreground">{label}</span></a> : <div key={title} className="rounded-xl border bg-card px-4 py-3"><span className="text-sm font-bold">{title}</span><span className="mt-1 block text-xs text-muted-foreground">{label}</span></div>)}</div><Callout label={locale === 'zh' ? '证据边界' : 'Evidence boundary'}>{c.sourceBoundary}</Callout></ContentSection>
    </WeekLayout>
  )
}
