/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChapterChapterIdRouteImport } from './routes/chapter.$chapterId'
import { Route as WeekWeekIdRouteImport } from './routes/week.$weekId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChapterChapterIdRoute = ChapterChapterIdRouteImport.update({
  id: '/chapter/$chapterId',
  path: '/chapter/$chapterId',
  getParentRoute: () => rootRouteImport,
} as any)
const WeekWeekIdRoute = WeekWeekIdRouteImport.update({
  id: '/week/$weekId',
  path: '/week/$weekId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chapter/$chapterId': typeof ChapterChapterIdRoute
  '/week/$weekId': typeof WeekWeekIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chapter/$chapterId': typeof ChapterChapterIdRoute
  '/week/$weekId': typeof WeekWeekIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chapter/$chapterId': typeof ChapterChapterIdRoute
  '/week/$weekId': typeof WeekWeekIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/chapter/$chapterId' | '/week/$weekId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/chapter/$chapterId' | '/week/$weekId'
  id: '__root__' | '/' | '/chapter/$chapterId' | '/week/$weekId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChapterChapterIdRoute: typeof ChapterChapterIdRoute
  WeekWeekIdRoute: typeof WeekWeekIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapter/$chapterId': {
      id: '/chapter/$chapterId'
      path: '/chapter/$chapterId'
      fullPath: '/chapter/$chapterId'
      preLoaderRoute: typeof ChapterChapterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/week/$weekId': {
      id: '/week/$weekId'
      path: '/week/$weekId'
      fullPath: '/week/$weekId'
      preLoaderRoute: typeof WeekWeekIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChapterChapterIdRoute: ChapterChapterIdRoute,
  WeekWeekIdRoute: WeekWeekIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
